In [1]:
import pandas as pd
from pathlib import Path

In [2]:
#calling in the 2019 pesticides table
pesticides_df = pd.read_csv(Path("2019_pesticide_by_county.csv"))
pesticides_df.head()

,AREA_FIPS_CODE,"2,4-D",ACEPHATE,ACETAMIPRID,ACETOCHLOR,ATRAZINE,AZOXYSTROBIN,BENTAZONE,BENZOVINDIFLUPYR,BOSCALID,...,TEBUCONAZOLE,TEBUPIRIMPHOS,TEBUTHIURON,TERBUFOS,TETRACONAZOLE,THIAMETHOXAM,THIOBENCARB,TRICLOPYR,TRIFLOXYSTROBIN,Grand Total
0,10001,12874.8,NaN,NaN,8918.9,32489.9,967.9,NaN,16.2,NaN,...,621.0,NaN,NaN,1895.9,NaN,NaN,NaN,NaN,226.1,213302.8
1,10003,1424.7,2.4,0.9,3130.3,8243.2,301.5,NaN,20.8,NaN,...,189.4,NaN,NaN,637.7,NaN,NaN,NaN,28.5,76.1,64162.0
2,10005,66354.3,NaN,NaN,30403.2,134910.1,3632.5,NaN,31.4,NaN,...,714.7,NaN,NaN,3671.2,NaN,NaN,NaN,NaN,437.9,648243.1
3,12001,12562.9,NaN,NaN,NaN,557.2,342.9,25.4,8.5,114.3,...,663.9,NaN,NaN,78.6,NaN,43.9,NaN,230.5,1.3,25143.6
4,12003,1576.3,NaN,NaN,26.6,146.7,119.0,NaN,17.0,0.1,...,3.8,NaN,NaN,41.8,1.0,NaN,NaN,195.8,0.5,3345.0

In [3]:
#filling in the null values with a 0
pesticides_df = pesticides_df.fillna(0)
pesticides_df.head()

,AREA_FIPS_CODE,"2,4-D",ACEPHATE,ACETAMIPRID,ACETOCHLOR,ATRAZINE,AZOXYSTROBIN,BENTAZONE,BENZOVINDIFLUPYR,BOSCALID,...,TEBUCONAZOLE,TEBUPIRIMPHOS,TEBUTHIURON,TERBUFOS,TETRACONAZOLE,THIAMETHOXAM,THIOBENCARB,TRICLOPYR,TRIFLOXYSTROBIN,Grand Total
0,10001,12874.8,0.0,0.0,8918.9,32489.9,967.9,0.0,16.2,0.0,...,621.0,0.0,0.0,1895.9,0.0,0.0,0.0,0.0,226.1,213302.8
1,10003,1424.7,2.4,0.9,3130.3,8243.2,301.5,0.0,20.8,0.0,...,189.4,0.0,0.0,637.7,0.0,0.0,0.0,28.5,76.1,64162.0
2,10005,66354.3,0.0,0.0,30403.2,134910.1,3632.5,0.0,31.4,0.0,...,714.7,0.0,0.0,3671.2,0.0,0.0,0.0,0.0,437.9,648243.1
3,12001,12562.9,0.0,0.0,0.0,557.2,342.9,25.4,8.5,114.3,...,663.9,0.0,0.0,78.6,0.0,43.9,0.0,230.5,1.3,25143.6
4,12003,1576.3,0.0,0.0,26.6,146.7,119.0,0.0,17.0,0.1,...,3.8,0.0,0.0,41.8,1.0,0.0,0.0,195.8,0.5,3345.0

In [4]:
#looking at each of the different column names/dataframe info
pesticides_df.info

<bound method DataFrame.info of      AREA_FIPS_CODE       2,4-D   ACEPHATE  ACETAMIPRID  ACETOCHLOR  \
0             10001     12874.8        0.0          0.0      8918.9
1             10003      1424.7        2.4          0.9      3130.3
2             10005     66354.3        0.0          0.0     30403.2
3             12001     12562.9        0.0          0.0         0.0
4             12003      1576.3        0.0          0.0        26.6
...             ...         ...        ...          ...         ...
3059          09009       166.7        0.0         26.6        90.7
3060          09011       398.3        0.0          6.3       687.2
3061          09013       283.1        0.0          9.9       506.8
3062          09015       340.2        0.0         12.6       620.8
3063    Grand Total  22361443.9  5855133.4      66748.7  27712782.3

        ATRAZINE  AZOXYSTROBIN  BENTAZONE  BENZOVINDIFLUPYR  BOSCALID  ...  \
0        32489.9         967.9        0.0              16.2       0.0  ...
1         8243.2         301.5        0.0              20.8       0.0  ...
2       134910.1        3632.5        0.0              31.4       0.0  ...
3          557.2         342.9       25.4               8.5     114.3  ...
4          146.7         119.0        0.0              17.0       0.1  ...
...          ...           ...        ...               ...       ...  ...
3059       176.8           0.1        0.0               0.0      15.7  ...
3060      1137.6           0.1        0.0               0.0       3.2  ...
3061       841.1           0.0        0.0               0.0       2.5  ...
3062      1019.1           0.0        0.0               0.0       7.6  ...
3063  33663059.4     1301556.7  1058728.9          150928.9  372891.2  ...

      TEBUCONAZOLE  TEBUPIRIMPHOS  TEBUTHIURON  TERBUFOS  TETRACONAZOLE  \
0            621.0            0.0          0.0    1895.9            0.0
1            189.4            0.0          0.0     637.7            0.0
2            714.7            0.0          0.0    3671.2            0.0
3            663.9            0.0          0.0      78.6            0.0
4              3.8            0.0          0.0      41.8            1.0
...            ...            ...          ...       ...            ...
3059           0.0            0.0          0.0       0.0            0.0
3060           0.0            0.0          0.0       0.0            0.0
3061           0.0            0.0          0.0       0.0            0.0
3062           0.0            0.0          0.0       0.0            0.0
3063      892076.7       112394.9       1932.1  768589.7       108574.2

      THIAMETHOXAM  THIOBENCARB  TRICLOPYR  TRIFLOXYSTROBIN  Grand Total
0              0.0          0.0        0.0            226.1     213302.8
1              0.0          0.0       28.5             76.1      64162.0
2              0.0          0.0        0.0            437.9     648243.1
3             43.9          0.0      230.5              1.3      25143.6
4              0.0          0.0      195.8              0.5       3345.0
...            ...          ...        ...              ...          ...
3059           3.3          0.0        0.0              9.4       1605.5
3060           2.2          0.0        0.0              1.7       8412.2
3061           6.3          0.0        0.0              1.5       6374.4
3062           2.1          0.0        0.0              4.5       7610.0
3063      145243.1     780582.2  1039730.6         471080.4  341070497.0

[3064 rows x 71 columns]>

In [5]:
#looking at each column name
pesticides_df.columns

Index(['AREA_FIPS_CODE', '2,4-D', 'ACEPHATE', 'ACETAMIPRID', 'ACETOCHLOR',
       'ATRAZINE', 'AZOXYSTROBIN', 'BENTAZONE', 'BENZOVINDIFLUPYR', 'BOSCALID',
       'BROMACIL', 'BROMOXYNIL', 'CARBARYL', 'CHLORANTRANILIPROLE',
       'CHLORIMURON', 'CHLORPYRIFOS', 'CLOTHIANIDIN', 'CYANTRANILIPROLE',
       'CYPRODINIL', 'DIAZINON', 'DICAMBA', 'DICROTOPHOS', 'DIFLUBENZURON',
       'DIMETHENAMID', 'DIMETHENAMID & DIMETHENAMID-P', 'DIMETHENAMID-P',
       'DIMETHOATE', 'DIMETHOMORPH', 'DINOTEFURAN', 'DIURON', 'ETHOPROPHOS',
       'ETOXAZOLE', 'FIPRONIL', 'FLUOMETURON', 'FLUOPICOLIDE', 'GLYPHOSATE',
       'HALOSULFURON', 'HEXAZINONE', 'IMAZETHAPYR', 'IMIDACLOPRID', 'LINURON',
       'MALATHION', 'METALAXYL', 'METCONAZOLE', 'METHOMYL', 'METHOXYFENOZIDE',
       'METOLACHLOR', 'METOLACHLOR & METOLACHLOR-S', 'METOLACHLOR-S',
       'METRIBUZIN', 'MYCLOBUTANIL', 'ORYZALIN', 'PERMETHRIN',
       'PIPERONYL BUTOXIDE', 'PROPAZINE', 'PROPICONAZOLE', 'PYRACLOSTROBIN',
       'PYRIMETHANIL', 'SIMAZINE', 'SULFENTRAZONE', 'SULFOXAFLOR',
       'TEBUCONAZOLE', 'TEBUPIRIMPHOS', 'TEBUTHIURON', 'TERBUFOS',
       'TETRACONAZOLE', 'THIAMETHOXAM', 'THIOBENCARB', 'TRICLOPYR',
       'TRIFLOXYSTROBIN', 'Grand Total'],
      dtype='object')

In [6]:
#dropping the grand total column since we don't really need it
pesticides_df = pesticides_df.drop(columns = "Grand Total")
pesticides_df

,AREA_FIPS_CODE,"2,4-D",ACEPHATE,ACETAMIPRID,ACETOCHLOR,ATRAZINE,AZOXYSTROBIN,BENTAZONE,BENZOVINDIFLUPYR,BOSCALID,...,SULFOXAFLOR,TEBUCONAZOLE,TEBUPIRIMPHOS,TEBUTHIURON,TERBUFOS,TETRACONAZOLE,THIAMETHOXAM,THIOBENCARB,TRICLOPYR,TRIFLOXYSTROBIN
0,10001,12874.8,0.0,0.0,8918.9,32489.9,967.9,0.0,16.2,0.0,...,0.0,621.0,0.0,0.0,1895.9,0.0,0.0,0.0,0.0,226.1
1,10003,1424.7,2.4,0.9,3130.3,8243.2,301.5,0.0,20.8,0.0,...,0.0,189.4,0.0,0.0,637.7,0.0,0.0,0.0,28.5,76.1
2,10005,66354.3,0.0,0.0,30403.2,134910.1,3632.5,0.0,31.4,0.0,...,0.0,714.7,0.0,0.0,3671.2,0.0,0.0,0.0,0.0,437.9
3,12001,12562.9,0.0,0.0,0.0,557.2,342.9,25.4,8.5,114.3,...,2.7,663.9,0.0,0.0,78.6,0.0,43.9,0.0,230.5,1.3
4,12003,1576.3,0.0,0.0,26.6,146.7,119.0,0.0,17.0,0.1,...,0.5,3.8,0.0,0.0,41.8,1.0,0.0,0.0,195.8,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3059,09009,166.7,0.0,26.6,90.7,176.8,0.1,0.0,0.0,15.7,...,0.0,0.0,0.0,0.0,0.0,0.0,3.3,0.0,0.0,9.4
3060,09011,398.3,0.0,6.3,687.2,1137.6,0.1,0.0,0.0,3.2,...,0.0,0.0,0.0,0.0,0.0,0.0,2.2,0.0,0.0,1.7
3061,09013,283.1,0.0,9.9,506.8,841.1,0.0,0.0,0.0,2.5,...,0.0,0.0,0.0,0.0,0.0,0.0,6.3,0.0,0.0,1.5
3062,09015,340.2,0.0,12.6,620.8,1019.1,0.0,0.0,0.0,7.6,...,0.0,0.0,0.0,0.0,0.0,0.0,2.1,0.0,0.0,4.5
3063,Grand Total,22361443.9,5855133.4,66748.7,27712782.3,33663059.4,1301556.7,1058728.9,150928.9,372891.2,...,91034.5,892076.7,112394.9,1932.1,768589.7,108574.2,145243.1,780582.2,1039730.6,471080.4

In [7]:
#creatng variables to hold specific columns that fall within that category 
insecticides = pesticides_df[["ACEPHATE", "ACETAMIPRID", "CARBARYL","CHLORANTRANILIPROLE",
                              "CHLORPYRIFOS","CLOTHIANIDIN","CYANTRANILIPROLE",
                              "DIAZINON","DICROTOPHOS","DIFLUBENZURON","DIMETHOATE",
                              "DINOTEFURAN","ETHOPROPHOS","ETOXAZOLE","FIPRONIL",
                              "IMIDACLOPRID","MALATHION","METHOMYL","METHOXYFENOZIDE",
                              "PERMETHRIN","SULFOXAFLOR","TEBUPIRIMPHOS","TERBUFOS",
                              "THIAMETHOXAM"]]
herbicides = pesticides_df[["2,4-D","ACETOCHLOR","ATRAZINE","BENTAZONE",
                            "BROMACIL","BROMOXYNIL","CHLORIMURON","DICAMBA",
                            "DIMETHENAMID","DIMETHENAMID & DIMETHENAMID-P",
                            "DIMETHENAMID-P","DIURON","FLUOMETURON","GLYPHOSATE",
                           "HALOSULFURON","HEXAZINONE","IMAZETHAPYR","LINURON","METOLACHLOR",
                           "METOLACHLOR & METOLACHLOR-S","METOLACHLOR-S","METRIBUZIN",
                           "ORYZALIN","PROPAZINE","SIMAZINE","SULFENTRAZONE","TEBUTHIURON",
                           "THIOBENCARB","TRICLOPYR"]]
fungicides = pesticides_df[["AZOXYSTROBIN","BENZOVINDIFLUPYR","BOSCALID","CYPRODINIL",
                           "DIMETHOMORPH","FLUOPICOLIDE","METALAXYL","METCONAZOLE",
                           "MYCLOBUTANIL","PROPICONAZOLE","PYRACLOSTROBIN","PYRIMETHANIL",
                           "TEBUCONAZOLE","TETRACONAZOLE","TRIFLOXYSTROBIN"]]
adjuvant = pesticides_df["PIPERONYL BUTOXIDE"]

In [8]:
#creating a new column into the pesticides_df referencing the created variables above
pesticides_df['Insecticide Sum'] = insecticides.sum(axis=1)
pesticides_df['Herbicide Sum'] = herbicides.sum(axis=1)
pesticides_df['Fungicide Sum'] = fungicides.sum(axis=1)
pesticides_df['Adjuvant Sum'] = adjuvant
pesticides_df.head()

,AREA_FIPS_CODE,"2,4-D",ACEPHATE,ACETAMIPRID,ACETOCHLOR,ATRAZINE,AZOXYSTROBIN,BENTAZONE,BENZOVINDIFLUPYR,BOSCALID,...,TERBUFOS,TETRACONAZOLE,THIAMETHOXAM,THIOBENCARB,TRICLOPYR,TRIFLOXYSTROBIN,Insecticide Sum,Herbicide Sum,Fungicide Sum,Adjuvant Sum
0,10001,12874.8,0.0,0.0,8918.9,32489.9,967.9,0.0,16.2,0.0,...,1895.9,0.0,0.0,0.0,0.0,226.1,5800.7,203083.5,4418.6,0.0
1,10003,1424.7,2.4,0.9,3130.3,8243.2,301.5,0.0,20.8,0.0,...,637.7,0.0,0.0,0.0,28.5,76.1,1935.5,60729.8,1496.7,0.0
2,10005,66354.3,0.0,0.0,30403.2,134910.1,3632.5,0.0,31.4,0.0,...,3671.2,0.0,0.0,0.0,0.0,437.9,10419.4,629484.6,8339.1,0.0
3,12001,12562.9,0.0,0.0,0.0,557.2,342.9,25.4,8.5,114.3,...,78.6,0.0,43.9,0.0,230.5,1.3,3536.4,20414.3,1192.9,0.0
4,12003,1576.3,0.0,0.0,26.6,146.7,119.0,0.0,17.0,0.1,...,41.8,1.0,0.0,0.0,195.8,0.5,246.9,2861.0,237.1,0.0

In [9]:
pesticides_df = pesticides_df.rename(columns = {'AREA_FIPS_CODE': 'FIPS'})
pesticides_df

,FIPS,"2,4-D",ACEPHATE,ACETAMIPRID,ACETOCHLOR,ATRAZINE,AZOXYSTROBIN,BENTAZONE,BENZOVINDIFLUPYR,BOSCALID,...,TERBUFOS,TETRACONAZOLE,THIAMETHOXAM,THIOBENCARB,TRICLOPYR,TRIFLOXYSTROBIN,Insecticide Sum,Herbicide Sum,Fungicide Sum,Adjuvant Sum
0,10001,12874.8,0.0,0.0,8918.9,32489.9,967.9,0.0,16.2,0.0,...,1895.9,0.0,0.0,0.0,0.0,226.1,5800.7,203083.5,4418.6,0.0
1,10003,1424.7,2.4,0.9,3130.3,8243.2,301.5,0.0,20.8,0.0,...,637.7,0.0,0.0,0.0,28.5,76.1,1935.5,60729.8,1496.7,0.0
2,10005,66354.3,0.0,0.0,30403.2,134910.1,3632.5,0.0,31.4,0.0,...,3671.2,0.0,0.0,0.0,0.0,437.9,10419.4,629484.6,8339.1,0.0
3,12001,12562.9,0.0,0.0,0.0,557.2,342.9,25.4,8.5,114.3,...,78.6,0.0,43.9,0.0,230.5,1.3,3536.4,20414.3,1192.9,0.0
4,12003,1576.3,0.0,0.0,26.6,146.7,119.0,0.0,17.0,0.1,...,41.8,1.0,0.0,0.0,195.8,0.5,246.9,2861.0,237.1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3059,09009,166.7,0.0,26.6,90.7,176.8,0.1,0.0,0.0,15.7,...,0.0,0.0,3.3,0.0,0.0,9.4,291.6,1223.7,90.2,0.0
3060,09011,398.3,0.0,6.3,687.2,1137.6,0.1,0.0,0.0,3.2,...,0.0,0.0,2.2,0.0,0.0,1.7,430.0,7897.6,84.6,0.0
3061,09013,283.1,0.0,9.9,506.8,841.1,0.0,0.0,0.0,2.5,...,0.0,0.0,6.3,0.0,0.0,1.5,374.8,5903.3,96.3,0.0
3062,09015,340.2,0.0,12.6,620.8,1019.1,0.0,0.0,0.0,7.6,...,0.0,0.0,2.1,0.0,0.0,4.5,448.0,7066.4,95.6,0.0
3063,Grand Total,22361443.9,5855133.4,66748.7,27712782.3,33663059.4,1301556.7,1058728.9,150928.9,372891.2,...,768589.7,108574.2,145243.1,780582.2,1039730.6,471080.4,14598036.4,320204392.9,6266201.4,1866.3

In [10]:
reduced_pesticides = pesticides_df[['FIPS', 'Insecticide Sum', 'Herbicide Sum', 'Fungicide Sum', 'Adjuvant Sum']]
reduced_pesticides

             FIPS  Insecticide Sum  Herbicide Sum  Fungicide Sum  Adjuvant Sum
0           10001           5800.7       203083.5         4418.6           0.0
1           10003           1935.5        60729.8         1496.7           0.0
2           10005          10419.4       629484.6         8339.1           0.0
3           12001           3536.4        20414.3         1192.9           0.0
4           12003            246.9         2861.0          237.1           0.0
...           ...              ...            ...            ...           ...
3059        09009            291.6         1223.7           90.2           0.0
3060        09011            430.0         7897.6           84.6           0.0
3061        09013            374.8         5903.3           96.3           0.0
3062        09015            448.0         7066.4           95.6           0.0
3063  Grand Total       14598036.4    320204392.9      6266201.4        1866.3

[3064 rows x 5 columns]

In [11]:
reduced_pesticides.dtypes

FIPS                object
Insecticide Sum    float64
Herbicide Sum      float64
Fungicide Sum      float64
Adjuvant Sum       float64
dtype: object

In [12]:
#calling in the cancer csv
cancer_df = pd.read_csv(Path("cancer_cleaned.csv"))
cancer_df.head(50)

,County,FIPS,"Age-Adjusted Incidence Rate([rate note]) - cases per 100,000",Lower 95% Confidence Interval,Upper 95% Confidence Interval,CI*Rank([rank note]),Lower CI (CI*Rank),Upper CI (CI*Rank),Average Annual Count,Recent Trend,Recent 5-Year Trend ([trend note]) in Incidence Rates,Lower 95% Confidence Interval.1,Upper 95% Confidence Interval.1
0,US (SEER+NPCR)(1),0,442.3,442,442.6,N/A,N/A,N/A,1698328,stable,-0.3,-0.6,0.1
1,"Union County, Florida(6)",12125,1237.4,1165.6,1312.8,N/A,1,1,237,stable,0.6,-0.5,1.9
2,"Palo Alto County, Iowa(7)",19147,658.1,591.1,731.1,N/A,1,6,82,rising,4.8,0.2,15.4
3,"Treasure County, Montana(6)",30103,652.2,401,1007.4,N/A,1,55,7,stable,-1.1,-5.6,3.3
4,"Polk County, Texas(7)",48373,633.6,604.6,663.7,N/A,1,4,425,rising,2.2,1.2,4.2
5,"Floyd County, Kentucky(7)",21071,616.8,584.3,650.7,N/A,1,19,295,stable,1.5,-1.8,5.3
6,"Logan County, Nebraska(6)",31113,609.8,406,888.8,N/A,1,84,7,*,*,*,*
7,"Lawrence County, Arkansas(6)",5075,599.8,553.6,649,N/A,1,10,136,rising,4.6,1.6,12.1
8,"Powell County, Kentucky(7)",21197,597.4,541,658.3,N/A,1,73,88,stable,0.8,-0.3,1.9
9,"Blaine County, Nebraska(6)",31009,595.9,349.1,972,N/A,1,87,4,stable,3.2,-1.1,8.9
10,"Golden Valley County, Montana(6)",30037,589.6,416.1,829.2,N/A,1,52,9,stable,0.1,-3.3,3.7
11,"Lincoln County, Kentucky(7)",21137,584.7,546.7,624.8,N/A,1,51,189,rising,0.7,0.3,1.1
12,"Logan County, West Virginia(6)",54045,583.8,551.2,617.9,N/A,1,7,268,stable,0.6,-0.3,1.5
13,"Lowndes County, Alabama(6)",1085,583.5,524.1,648.3,N/A,1,10,79,stable,1.7,0,3.5
14,"Mercer County, Kentucky(7)",21167,581.5,542,623.3,N/A,1,56,175,stable,0.8,-0.2,1.9
15,"Perry County, Kentucky(7)",21193,578.1,541.1,617.2,N/A,1,53,196,stable,0.5,-0.4,1.5
16,"Fleming County, Kentucky(7)",21069,576,527.2,628.3,N/A,1,77,110,stable,0.4,-0.8,1.7
17,"Grant County, Kentucky(7)",21081,575.7,535.7,618.1,N/A,1,62,162,rising,0.7,0.1,1.4
18,"Pickens County, Georgia(7)",13227,575.3,543.4,608.8,N/A,1,17,277,rising,1.1,0.3,2.1
19,"Adams County, Wisconsin(6)",55001,575.1,536.9,615.9,N/A,1,7,219,stable,0,-0.8,0.9
20,"Owsley County, Kentucky(7)",21189,574.9,490,671.5,N/A,1,116,36,stable,0.2,-2,2.6
21,"Bath County, Kentucky(7)",21011,574.8,521.2,632.6,N/A,1,84,90,stable,-0.4,-5.3,0.6
22,"Lee County, Kentucky(7)",21129,574.7,506.2,650.6,N/A,1,109,56,stable,0.1,-1.7,1.9
23,"Lee County, Georgia(7)",13177,573.6,535.2,614,N/A,1,29,179,rising,1.3,0.3,2.6
24,"Monroe County, Kentucky(7)",21171,572.4,515.9,633.8,N/A,1,98,82,rising,2.4,1.1,3.7
25,"Yukon-Koyukuk Census Area, Alaska(6)",2290,569,481.1,668.5,N/A,1,7,34,stable,1,-2,4.5
26,"Livingston County, Kentucky(7)",21139,568.9,510.4,633,N/A,1,96,79,stable,0.4,-0.8,1.6
27,"Scott County, Illinois(7)",17171,568.6,488.7,658.9,N/A,1,91,40,stable,1.3,-0.1,2.8
28,"Taylor County, Kentucky(7)",21217,568.1,530.4,607.9,N/A,1,67,184,stable,-3.5,-8.8,1.4
29,"Cass County, Iowa(7)",19029,567.8,518.4,621,N/A,1,52,113,rising,0.9,0.1,1.7
30,"Menard County, Illinois(7)",17129,567.2,516.1,622.4,N/A,1,52,99,stable,0.3,-0.5,1.2
31,"Clay County, Kentucky(7)",21051,566.4,523.8,611.6,N/A,1,79,138,stable,-1,-4.6,0.3
32,"McDuffie County, Georgia(7)",13189,566.3,525.6,609.6,N/A,1,41,156,stable,1,-0.1,2.1
33,"Pleasants County, West Virginia(6)",54073,566.2,501.3,638.1,N/A,1,36,58,stable,0.3,-1.2,2
34,"Knox County, Kentucky(7)",21121,566.2,532.6,601.5,N/A,1,67,224,stable,0.5,-0.4,1.3
35,"Lawrence County, Kentucky(7)",21127,565.7,518.8,615.9,N/A,1,84,116,stable,0.8,0,1.6
36,"Marion County, Illinois(7)",17121,565.4,535.4,596.8,N/A,1,25,290,stable,0.2,-0.4,0.8
37,"Hitchcock County, Nebraska(6)",31087,563.9,457.2,690.4,N/A,1,65,24,stable,0.6,-1.8,2.9
38,"Jefferson County, New York(7)",36045,562.7,543.2,582.7,N/A,1,8,658,stable,2,-0.8,5
39,"Trousdale County, Tennessee(6)",47169,561.5,499.9,628.7,N/A,1,53,64,rising,1.4,0.2,2.8
40,"Bryan County, Georgia(7)",13029,561,525.9,597.8,N/A,1,37,199,stable,0.8,0,1.7
41,"Iberville Parish, Louisiana(7)",22047,560.3,527.4,594.8,N/A,1,13,227,stable,3.3,-0.2,6
42,"Stonewall County, Texas(7)",48433,560.2,412.3,749.4,N/A,1,241,11,stable,1.7,-1.6,5.3
43,"Lewis County, West Virginia(6)",54041,560.2,516.2,607.3,N/A,1,23,129,stable,0.4,-1.3,2.1
44,"Harlan County, Kentucky(7)",21095,559.5,523.7,597.2,N/A,1,72,200,stable,0.7,-0.2,1.6
45,"Aurora County, South Dakota(6)",46003,559.4,454.8,682.8,N/A,1,52,23,stable,1.9,-0.3,4.3
46,"Cape May County, New Jersey(7)",34009,559,541,577.4,N/A,1,2,900,stable,-0.4,-4.2,0.8
47,"McCook County, South Dakota(6)",46087,558.8,482.1,645,N/A,1,38,41,stable,0.9,-0.5,2.3
48,"Greeley County, Nebraska(6)",31077,557.8,440.4,699.2,N/A,1,74,20,stable,0.4,-2.6,3.4
49,"Adair County, Kentucky(7)",21001,557.4,515.5,602.1,N/A,1,83,143,stable,0.5,-0.3,1.5

In [13]:
#looking at the columns of the cancer df
cancer_df.columns

Index(['County', ' FIPS',
       'Age-Adjusted Incidence Rate([rate note]) - cases per 100,000',
       'Lower 95% Confidence Interval', 'Upper 95% Confidence Interval',
       'CI*Rank([rank note])', 'Lower CI (CI*Rank)', 'Upper CI (CI*Rank)',
       'Average Annual Count', 'Recent Trend',
       'Recent 5-Year Trend ([trend note]) in Incidence Rates',
       'Lower 95% Confidence Interval.1', 'Upper 95% Confidence Interval.1'],
      dtype='object')

In [14]:
#reducing the columns to only the ones that we want to look at 
reduced_cancer = cancer_df[["County", " FIPS", "Age-Adjusted Incidence Rate([rate note]) - cases per 100,000"]]
reduced_cancer.head()

,County,FIPS,"Age-Adjusted Incidence Rate([rate note]) - cases per 100,000"
0,US (SEER+NPCR)(1),0,442.3
1,"Union County, Florida(6)",12125,1237.4
2,"Palo Alto County, Iowa(7)",19147,658.1
3,"Treasure County, Montana(6)",30103,652.2
4,"Polk County, Texas(7)",48373,633.6

In [15]:
#renaming the columns to be more legible/short
renamed_cancer = reduced_cancer.rename(columns = {' FIPS': 'FIPS', 'Age-Adjusted Incidence Rate([rate note]) - cases per 100,000':'Cancer Incidence Rate Per 100k'})
renamed_cancer.head(30)

                                  County   FIPS Cancer Incidence Rate Per 100k
0                      US (SEER+NPCR)(1)      0                          442.3
1               Union County, Florida(6)  12125                         1237.4
2              Palo Alto County, Iowa(7)  19147                          658.1
3            Treasure County, Montana(6)  30103                          652.2
4                  Polk County, Texas(7)  48373                          633.6
5              Floyd County, Kentucky(7)  21071                          616.8
6              Logan County, Nebraska(6)  31113                          609.8
7           Lawrence County, Arkansas(6)   5075                          599.8
8             Powell County, Kentucky(7)  21197                          597.4
9             Blaine County, Nebraska(6)  31009                          595.9
10      Golden Valley County, Montana(6)  30037                          589.6
11           Lincoln County, Kentucky(7)  21137                          584.7
12        Logan County, West Virginia(6)  54045                          583.8
13            Lowndes County, Alabama(6)   1085                          583.5
14            Mercer County, Kentucky(7)  21167                          581.5
15             Perry County, Kentucky(7)  21193                          578.1
16           Fleming County, Kentucky(7)  21069                            576
17             Grant County, Kentucky(7)  21081                          575.7
18            Pickens County, Georgia(7)  13227                          575.3
19            Adams County, Wisconsin(6)  55001                          575.1
20            Owsley County, Kentucky(7)  21189                          574.9
21              Bath County, Kentucky(7)  21011                          574.8
22               Lee County, Kentucky(7)  21129                          574.7
23                Lee County, Georgia(7)  13177                          573.6
24            Monroe County, Kentucky(7)  21171                          572.4
25  Yukon-Koyukuk Census Area, Alaska(6)   2290                            569
26        Livingston County, Kentucky(7)  21139                          568.9
27             Scott County, Illinois(7)  17171                          568.6
28            Taylor County, Kentucky(7)  21217                          568.1
29                  Cass County, Iowa(7)  19029                          567.8

In [16]:
renamed_cancer.dtypes

County                            object
FIPS                               int64
Cancer Incidence Rate Per 100k    object
dtype: object

In [17]:
#converting the fips column from the cancer table into a a string(object)
renamed_cancer = renamed_cancer.astype({'FIPS': str}, errors = 'raise')

In [18]:
renamed_cancer.dtypes

County                            object
FIPS                              object
Cancer Incidence Rate Per 100k    object
dtype: object

In [19]:
breast_cancer = pd.read_csv(Path("breast_cancer.csv"))
breast_cancer.head()

,County,FIPS,"Age-Adjusted Incidence Rate([rate note]) - cases per 100,000",Lower 95% Confidence Interval,Upper 95% Confidence Interval,CI*Rank([rank note]),Lower CI (CI*Rank),Upper CI (CI*Rank),Average Annual Count,Recent Trend,Recent 5-Year Trend ([trend note]) in Incidence Rates,Lower 95% Confidence Interval.1,Upper 95% Confidence Interval.1
0,US (SEER+NPCR)(1),0.0,127,126.8,127.2,N/A,N/A,N/A,249750,rising,0.5,0.3,0.7
1,"Webster County, Georgia(7)",13307.0,250.6,153.7,393.4,N/A,1,143,5,*,*,*,*
2,"Aurora County, South Dakota(6)",46003.0,239.7,139.6,385.8,N/A,1,32,4,rising,28.6,1.9,71.9
3,"Pickens County, Alabama(6)",1107.0,213,176.3,255.4,N/A,1,5,27,rising,4.6,1.9,7.8
4,"Nantucket County, Massachusetts(7)",25019.0,209.5,161.2,268.1,N/A,1,2,14,stable,1.1,-1.1,3.5

In [20]:
renamed_breast_cancer = breast_cancer.rename(columns = {' FIPS': 'FIPS', 'Age-Adjusted Incidence Rate([rate note]) - cases per 100,000':'Breast Cancer Incidence Rate Per 100k'})
renamed_breast_cancer.head(30)

,County,FIPS,Breast Cancer Incidence Rate Per 100k,Lower 95% Confidence Interval,Upper 95% Confidence Interval,CI*Rank([rank note]),Lower CI (CI*Rank),Upper CI (CI*Rank),Average Annual Count,Recent Trend,Recent 5-Year Trend ([trend note]) in Incidence Rates,Lower 95% Confidence Interval.1,Upper 95% Confidence Interval.1
0,US (SEER+NPCR)(1),0.0,127,126.8,127.2,N/A,N/A,N/A,249750,rising,0.5,0.3,0.7
1,"Webster County, Georgia(7)",13307.0,250.6,153.7,393.4,N/A,1,143,5,*,*,*,*
2,"Aurora County, South Dakota(6)",46003.0,239.7,139.6,385.8,N/A,1,32,4,rising,28.6,1.9,71.9
3,"Pickens County, Alabama(6)",1107.0,213,176.3,255.4,N/A,1,5,27,rising,4.6,1.9,7.8
4,"Nantucket County, Massachusetts(7)",25019.0,209.5,161.2,268.1,N/A,1,2,14,stable,1.1,-1.1,3.5
5,"Hitchcock County, Nebraska(6)",31087.0,204.6,114.7,341.2,N/A,1,60,4,*,*,*,*
6,"Tishomingo County, Mississippi(6)",28141.0,198.3,164.1,238,N/A,1,14,27,rising,7.6,4.9,11.2
7,"Mountrail County, North Dakota(6)",38061.0,197,142.2,265.6,N/A,1,22,9,stable,3.2,-0.4,8.1
8,"Fallon County, Montana(6)",30025.0,196.9,110.1,326.8,N/A,1,37,3,*,*,*,*
9,"Pleasants County, West Virginia(6)",54073.0,196.2,139.9,269.2,N/A,1,32,9,rising,5.4,0.3,12.5
10,"Union County, Florida(6)",12125.0,194.9,144.7,256.7,N/A,1,40,11,stable,0.8,-2.2,4.2
11,"Hood River County, Oregon(6)",41027.0,187.3,155.6,223.8,N/A,1,7,26,stable,2.5,-1.6,7.2
12,"Towns County, Georgia(7)",13281.0,186.3,141.2,242.7,N/A,1,103,18,stable,2.9,-0.2,6.5
13,"Warren County, Georgia(7)",13301.0,184.1,123.8,265.6,N/A,1,136,8,*,*,*,*
14,"Price County, Wisconsin(6)",55099.0,183.5,143.4,232.5,N/A,1,52,19,stable,2.9,-1.1,7.5
15,"Stanley County, South Dakota(6)",46117.0,183.1,99.6,309.1,N/A,1,39,3,*,*,*,*
16,"Johnson County, Nebraska(6)",31097.0,182.8,108.3,289.2,N/A,1,60,5,rising,18.2,3.1,54.5
17,"Calhoun County, Georgia(7)",13037.0,181.6,117.6,269.5,N/A,1,146,6,stable,8,-1,45.1
18,"Shelby County, Missouri(6)",29205.0,181.5,121,262.1,N/A,1,101,7,stable,4,-0.3,9.1
19,"Burnett County, Wisconsin(6)",55013.0,180.9,145,224.4,N/A,1,50,23,stable,2.3,-1.5,6.8
20,"McCook County, South Dakota(6)",46087.0,178.9,120.4,257.7,N/A,1,31,7,stable,6.8,-0.5,34.6
21,"Clay County, Nebraska(6)",31035.0,176.6,122,249.3,N/A,1,55,8,rising,5,1.2,10.1
22,"Calhoun County, Illinois(7)",17013.0,176.4,121,254.1,N/A,1,97,7,stable,3.2,-1.8,9.6
23,"Harrison County, Iowa(7)",19085.0,176.2,138.3,222.1,N/A,1,70,17,rising,1.5,0.2,2.9
24,"McLean County, North Dakota(6)",38055.0,175.4,125,239.4,N/A,1,26,10,stable,1.7,-3.9,7.9
25,"Keokuk County, Iowa(7)",19107.0,174.9,128.3,233.3,N/A,1,85,11,stable,1.8,-0.4,4.3
26,"Pocahontas County, Iowa(7)",19151.0,174.5,119.2,247.9,N/A,1,92,8,stable,0.6,-1.2,2.5
27,"Stillwater County, Montana(6)",30095.0,174.4,128.9,232.3,N/A,1,28,12,stable,1.4,-2.2,5.7
28,"Lafayette County, Wisconsin(6)",55065.0,174,137.4,217.7,N/A,1,58,18,rising,3.4,0.3,7
29,"Kingsbury County, South Dakota(6)",46077.0,171.9,114.3,252.2,N/A,1,32,7,stable,2.1,-3.1,8.8

In [21]:
renamed_breast_cancer.dtypes

County                                                    object
FIPS                                                     float64
Breast Cancer Incidence Rate Per 100k                     object
Lower 95% Confidence Interval                             object
Upper 95% Confidence Interval                             object
CI*Rank([rank note])                                      object
Lower CI (CI*Rank)                                        object
Upper CI (CI*Rank)                                        object
Average Annual Count                                      object
Recent Trend                                              object
Recent 5-Year Trend ([trend note]) in Incidence Rates     object
Lower 95% Confidence Interval.1                           object
Upper 95% Confidence Interval.1                           object
dtype: object

In [22]:
renamed_breast_cancer = renamed_breast_cancer.astype({'FIPS': str}, errors = 'raise')

In [23]:
renamed_breast_cancer.dtypes

County                                                   object
FIPS                                                     object
Breast Cancer Incidence Rate Per 100k                    object
Lower 95% Confidence Interval                            object
Upper 95% Confidence Interval                            object
CI*Rank([rank note])                                     object
Lower CI (CI*Rank)                                       object
Upper CI (CI*Rank)                                       object
Average Annual Count                                     object
Recent Trend                                             object
Recent 5-Year Trend ([trend note]) in Incidence Rates    object
Lower 95% Confidence Interval.1                          object
Upper 95% Confidence Interval.1                          object
dtype: object

In [24]:
leukemia = pd.read_csv(Path("leukemia.csv"))
leukemia.head()

,County,FIPS,"Age-Adjusted Incidence Rate([rate note]) - cases per 100,000",Lower 95% Confidence Interval,Upper 95% Confidence Interval,CI*Rank([rank note]),Lower CI (CI*Rank),Upper CI (CI*Rank),Average Annual Count,Recent Trend,Recent 5-Year Trend ([trend note]) in Incidence Rates,Lower 95% Confidence Interval.1,Upper 95% Confidence Interval.1
0,US (SEER+NPCR)(1),0.0,13.9,13.9,14,N/A,N/A,N/A,51518,falling,-1.9,-2.3,-1.4
1,"Union County, Florida(6)",12125.0,56.5,41.8,75,N/A,1,1,10,rising,14.5,5.6,37.1
2,"Emmet County, Iowa(7)",19063.0,33.6,19.8,54,N/A,1,56,4,*,*,*,*
3,"Floyd County, Iowa(7)",19067.0,29.2,19.3,42.8,N/A,1,44,6,stable,2.6,-0.6,6.3
4,"Lawrence County, Arkansas(6)",5075.0,27.7,17.9,41.1,N/A,1,28,6,rising,6.8,0.9,15.9

In [25]:
renamed_leukemia = leukemia.rename(columns = {' FIPS': 'FIPS', 'Age-Adjusted Incidence Rate([rate note]) - cases per 100,000':'Leukemia Incidence Rate Per 100k'})
renamed_leukemia.head()

,County,FIPS,Leukemia Incidence Rate Per 100k,Lower 95% Confidence Interval,Upper 95% Confidence Interval,CI*Rank([rank note]),Lower CI (CI*Rank),Upper CI (CI*Rank),Average Annual Count,Recent Trend,Recent 5-Year Trend ([trend note]) in Incidence Rates,Lower 95% Confidence Interval.1,Upper 95% Confidence Interval.1
0,US (SEER+NPCR)(1),0.0,13.9,13.9,14,N/A,N/A,N/A,51518,falling,-1.9,-2.3,-1.4
1,"Union County, Florida(6)",12125.0,56.5,41.8,75,N/A,1,1,10,rising,14.5,5.6,37.1
2,"Emmet County, Iowa(7)",19063.0,33.6,19.8,54,N/A,1,56,4,*,*,*,*
3,"Floyd County, Iowa(7)",19067.0,29.2,19.3,42.8,N/A,1,44,6,stable,2.6,-0.6,6.3
4,"Lawrence County, Arkansas(6)",5075.0,27.7,17.9,41.1,N/A,1,28,6,rising,6.8,0.9,15.9

In [26]:
renamed_leukemia.dtypes

County                                                    object
FIPS                                                     float64
Leukemia Incidence Rate Per 100k                          object
Lower 95% Confidence Interval                             object
Upper 95% Confidence Interval                             object
CI*Rank([rank note])                                      object
Lower CI (CI*Rank)                                        object
Upper CI (CI*Rank)                                        object
Average Annual Count                                      object
Recent Trend                                              object
Recent 5-Year Trend ([trend note]) in Incidence Rates     object
Lower 95% Confidence Interval.1                           object
Upper 95% Confidence Interval.1                           object
dtype: object

In [27]:
renamed_leukemia = renamed_leukemia.astype({'FIPS': str}, errors = 'raise')

In [28]:
renamed_leukemia.dtypes

County                                                   object
FIPS                                                     object
Leukemia Incidence Rate Per 100k                         object
Lower 95% Confidence Interval                            object
Upper 95% Confidence Interval                            object
CI*Rank([rank note])                                     object
Lower CI (CI*Rank)                                       object
Upper CI (CI*Rank)                                       object
Average Annual Count                                     object
Recent Trend                                             object
Recent 5-Year Trend ([trend note]) in Incidence Rates    object
Lower 95% Confidence Interval.1                          object
Upper 95% Confidence Interval.1                          object
dtype: object

In [29]:
lung_cancer = pd.read_csv(Path("lung_and_bronchus.csv"))
lung_cancer.head()

,County,FIPS,"Age-Adjusted Incidence Rate([rate note]) - cases per 100,000",Lower 95% Confidence Interval,Upper 95% Confidence Interval,CI*Rank([rank note]),Lower CI (CI*Rank),Upper CI (CI*Rank),Average Annual Count,Recent Trend,Recent 5-Year Trend ([trend note]) in Incidence Rates,Lower 95% Confidence Interval.1,Upper 95% Confidence Interval.1
0,US (SEER+NPCR)(1),0.0,54,53.9,54.1,N/A,N/A,N/A,215307,falling,-1.8,-2,-1.7
1,"Union County, Florida(6)",12125.0,182.9,156.7,212.5,N/A,1,1,37,stable,-1.9,-4.1,0.4
2,"Owsley County, Kentucky(7)",21189.0,141.9,102.4,193.5,N/A,1,92,9,stable,1.3,-1.5,4.4
3,"Mississippi County, Missouri(6)",29133.0,132.3,109.5,158.9,N/A,1,14,24,stable,2.1,0,4.4
4,"Carroll County, Kentucky(7)",21041.0,131.5,105.5,162.4,N/A,1,62,18,stable,0.6,-1.6,3.1

In [30]:
renamed_lung_cancer = lung_cancer.rename(columns = {' FIPS': 'FIPS', 'Age-Adjusted Incidence Rate([rate note]) - cases per 100,000':'Lung Cancer Incidence Rate Per 100k'})
renamed_lung_cancer.head()

,County,FIPS,Lung Cancer Incidence Rate Per 100k,Lower 95% Confidence Interval,Upper 95% Confidence Interval,CI*Rank([rank note]),Lower CI (CI*Rank),Upper CI (CI*Rank),Average Annual Count,Recent Trend,Recent 5-Year Trend ([trend note]) in Incidence Rates,Lower 95% Confidence Interval.1,Upper 95% Confidence Interval.1
0,US (SEER+NPCR)(1),0.0,54,53.9,54.1,N/A,N/A,N/A,215307,falling,-1.8,-2,-1.7
1,"Union County, Florida(6)",12125.0,182.9,156.7,212.5,N/A,1,1,37,stable,-1.9,-4.1,0.4
2,"Owsley County, Kentucky(7)",21189.0,141.9,102.4,193.5,N/A,1,92,9,stable,1.3,-1.5,4.4
3,"Mississippi County, Missouri(6)",29133.0,132.3,109.5,158.9,N/A,1,14,24,stable,2.1,0,4.4
4,"Carroll County, Kentucky(7)",21041.0,131.5,105.5,162.4,N/A,1,62,18,stable,0.6,-1.6,3.1

In [31]:
renamed_lung_cancer = renamed_lung_cancer.astype({'FIPS': str}, errors = 'raise')

In [32]:
renamed_lung_cancer.dtypes

County                                                   object
FIPS                                                     object
Lung Cancer Incidence Rate Per 100k                      object
Lower 95% Confidence Interval                            object
Upper 95% Confidence Interval                            object
CI*Rank([rank note])                                     object
Lower CI (CI*Rank)                                       object
Upper CI (CI*Rank)                                       object
Average Annual Count                                     object
Recent Trend                                             object
Recent 5-Year Trend ([trend note]) in Incidence Rates    object
Lower 95% Confidence Interval.1                          object
Upper 95% Confidence Interval.1                          object
dtype: object

In [33]:
non_hodgkin_lymphoma = pd.read_csv(Path("non-hodgkin_lymphoma.csv"))
non_hodgkin_lymphoma.head()

,County,FIPS,"Age-Adjusted Incidence Rate([rate note]) - cases per 100,000",Lower 95% Confidence Interval,Upper 95% Confidence Interval,CI*Rank([rank note]),Lower CI (CI*Rank),Upper CI (CI*Rank),Average Annual Count,Recent Trend,Recent 5-Year Trend ([trend note]) in Incidence Rates,Lower 95% Confidence Interval.1,Upper 95% Confidence Interval.1
0,US (SEER+NPCR)(1),0.0,18.6,18.5,18.7,N/A,N/A,N/A,70394,falling,-1.3,-1.5,-0.9
1,"Union County, Florida(6)",12125.0,48.5,35,65.9,N/A,1,3,9,stable,0,-4.4,4.9
2,"Butler County, Nebraska(6)",31023.0,47.9,31.2,71.4,N/A,1,5,6,*,*,*,*
3,"Fulton County, Arkansas(6)",5049.0,41.7,27.4,61,N/A,1,20,7,*,*,*,*
4,"Moody County, South Dakota(6)",46101.0,40.2,22.1,67.7,N/A,1,11,3,*,*,*,*

In [34]:
non_hodgkin_lymphoma_renamed = non_hodgkin_lymphoma.rename(columns = {' FIPS': 'FIPS', 'Age-Adjusted Incidence Rate([rate note]) - cases per 100,000':'Non-Hodgkin Lymphoma Incidence Rate Per 100k'})
non_hodgkin_lymphoma_renamed.head()

,County,FIPS,Non-Hodgkin Lymphoma Incidence Rate Per 100k,Lower 95% Confidence Interval,Upper 95% Confidence Interval,CI*Rank([rank note]),Lower CI (CI*Rank),Upper CI (CI*Rank),Average Annual Count,Recent Trend,Recent 5-Year Trend ([trend note]) in Incidence Rates,Lower 95% Confidence Interval.1,Upper 95% Confidence Interval.1
0,US (SEER+NPCR)(1),0.0,18.6,18.5,18.7,N/A,N/A,N/A,70394,falling,-1.3,-1.5,-0.9
1,"Union County, Florida(6)",12125.0,48.5,35,65.9,N/A,1,3,9,stable,0,-4.4,4.9
2,"Butler County, Nebraska(6)",31023.0,47.9,31.2,71.4,N/A,1,5,6,*,*,*,*
3,"Fulton County, Arkansas(6)",5049.0,41.7,27.4,61,N/A,1,20,7,*,*,*,*
4,"Moody County, South Dakota(6)",46101.0,40.2,22.1,67.7,N/A,1,11,3,*,*,*,*

In [35]:
non_hodgkin_lymphoma_renamed = non_hodgkin_lymphoma_renamed.astype({'FIPS': str}, errors = 'raise')

In [36]:
non_hodgkin_lymphoma_renamed.dtypes

County                                                   object
FIPS                                                     object
Non-Hodgkin Lymphoma Incidence Rate Per 100k             object
Lower 95% Confidence Interval                            object
Upper 95% Confidence Interval                            object
CI*Rank([rank note])                                     object
Lower CI (CI*Rank)                                       object
Upper CI (CI*Rank)                                       object
Average Annual Count                                     object
Recent Trend                                             object
Recent 5-Year Trend ([trend note]) in Incidence Rates    object
Lower 95% Confidence Interval.1                          object
Upper 95% Confidence Interval.1                          object
dtype: object

In [37]:
prostate_cancer = pd.read_csv(Path("prostate.csv"))
prostate_cancer.head()

,County,FIPS,"Age-Adjusted Incidence Rate([rate note]) - cases per 100,000",Lower 95% Confidence Interval,Upper 95% Confidence Interval,CI*Rank([rank note]),Lower CI (CI*Rank),Upper CI (CI*Rank),Average Annual Count,Recent Trend,Recent 5-Year Trend ([trend note]) in Incidence Rates,Lower 95% Confidence Interval.1,Upper 95% Confidence Interval.1
0,US (SEER+NPCR)(1),0.0,110.5,110.2,110.7,N/A,N/A,N/A,212734,rising,2.5,1,4.1
1,"Union County, Florida(6)",12125.0,295.7,253.3,344,N/A,1,1,39,stable,1.6,-1.8,6
2,"Wheatland County, Montana(6)",30107.0,258.5,162.8,403.6,N/A,1,29,5,rising,64.5,31.3,130.2
3,"Greeley County, Nebraska(6)",31077.0,229.1,139.6,365.4,N/A,1,53,5,rising,12.9,0.7,47.9
4,"Boone County, Nebraska(6)",31011.0,226.7,168.1,303.8,N/A,1,24,10,stable,0,-5.5,6

In [38]:
prostate_renamed = prostate_cancer.rename(columns = {' FIPS': 'FIPS', 'Age-Adjusted Incidence Rate([rate note]) - cases per 100,000':'Prostate Cancer Incidence Rate Per 100k'})
prostate_renamed.head()

,County,FIPS,Prostate Cancer Incidence Rate Per 100k,Lower 95% Confidence Interval,Upper 95% Confidence Interval,CI*Rank([rank note]),Lower CI (CI*Rank),Upper CI (CI*Rank),Average Annual Count,Recent Trend,Recent 5-Year Trend ([trend note]) in Incidence Rates,Lower 95% Confidence Interval.1,Upper 95% Confidence Interval.1
0,US (SEER+NPCR)(1),0.0,110.5,110.2,110.7,N/A,N/A,N/A,212734,rising,2.5,1,4.1
1,"Union County, Florida(6)",12125.0,295.7,253.3,344,N/A,1,1,39,stable,1.6,-1.8,6
2,"Wheatland County, Montana(6)",30107.0,258.5,162.8,403.6,N/A,1,29,5,rising,64.5,31.3,130.2
3,"Greeley County, Nebraska(6)",31077.0,229.1,139.6,365.4,N/A,1,53,5,rising,12.9,0.7,47.9
4,"Boone County, Nebraska(6)",31011.0,226.7,168.1,303.8,N/A,1,24,10,stable,0,-5.5,6

In [39]:
prostate_renamed = prostate_renamed.astype({'FIPS': str}, errors = 'raise')

In [40]:
prostate_renamed.dtypes

County                                                   object
FIPS                                                     object
Prostate Cancer Incidence Rate Per 100k                  object
Lower 95% Confidence Interval                            object
Upper 95% Confidence Interval                            object
CI*Rank([rank note])                                     object
Lower CI (CI*Rank)                                       object
Upper CI (CI*Rank)                                       object
Average Annual Count                                     object
Recent Trend                                             object
Recent 5-Year Trend ([trend note]) in Incidence Rates    object
Lower 95% Confidence Interval.1                          object
Upper 95% Confidence Interval.1                          object
dtype: object

In [41]:
breast = renamed_breast_cancer["Breast Cancer Incidence Rate Per 100k"]
leukemia = renamed_leukemia["Leukemia Incidence Rate Per 100k"]
lung = renamed_lung_cancer["Lung Cancer Incidence Rate Per 100k"]
lymphoma = non_hodgkin_lymphoma_renamed["Non-Hodgkin Lymphoma Incidence Rate Per 100k"]
prostate = prostate_renamed["Prostate Cancer Incidence Rate Per 100k"]

In [42]:
renamed_cancer["Breast Cancer Incidence Rate Per 100k"] = breast
renamed_cancer["Leukemia Incidence Rate Per 100k"] = leukemia
renamed_cancer["Lung Cancer Incidence Rate Per 100k"] = lung
renamed_cancer["Non-Hodgkin Lymphoma Incidence Rate Per 100k"] = lymphoma
renamed_cancer["Prostate Cancer Incidence Rate Per 100k"] = prostate
renamed_cancer.head(50)

,County,FIPS,Cancer Incidence Rate Per 100k,Breast Cancer Incidence Rate Per 100k,Leukemia Incidence Rate Per 100k,Lung Cancer Incidence Rate Per 100k,Non-Hodgkin Lymphoma Incidence Rate Per 100k,Prostate Cancer Incidence Rate Per 100k
0,US (SEER+NPCR)(1),0,442.3,127,13.9,54,18.6,110.5
1,"Union County, Florida(6)",12125,1237.4,250.6,56.5,182.9,48.5,295.7
2,"Palo Alto County, Iowa(7)",19147,658.1,239.7,33.6,141.9,47.9,258.5
3,"Treasure County, Montana(6)",30103,652.2,213,29.2,132.3,41.7,229.1
4,"Polk County, Texas(7)",48373,633.6,209.5,27.7,131.5,40.2,226.7
5,"Floyd County, Kentucky(7)",21071,616.8,204.6,27.7,127.7,36.7,225.7
6,"Logan County, Nebraska(6)",31113,609.8,198.3,27.2,126.4,34.7,219.4
7,"Lawrence County, Arkansas(6)",5075,599.8,197,26.9,126.2,34.6,215.7
8,"Powell County, Kentucky(7)",21197,597.4,196.9,26.5,125.5,32.9,212.1
9,"Blaine County, Nebraska(6)",31009,595.9,196.2,26.3,123.6,32.1,207.7
10,"Golden Valley County, Montana(6)",30037,589.6,194.9,26.3,123.6,31.6,206.3
11,"Lincoln County, Kentucky(7)",21137,584.7,187.3,26.1,123.4,30.8,205.9
12,"Logan County, West Virginia(6)",54045,583.8,186.3,26,121.7,30.7,204.9
13,"Lowndes County, Alabama(6)",1085,583.5,184.1,25.7,120.7,30.5,200.2
14,"Mercer County, Kentucky(7)",21167,581.5,183.5,25.6,119.7,30.2,199
15,"Perry County, Kentucky(7)",21193,578.1,183.1,25.3,119.2,30.2,197.1
16,"Fleming County, Kentucky(7)",21069,576,182.8,25.2,116.7,30.1,197
17,"Grant County, Kentucky(7)",21081,575.7,181.6,24.9,116.7,30,195.2
18,"Pickens County, Georgia(7)",13227,575.3,181.5,24.8,116.4,29.9,192.4
19,"Adams County, Wisconsin(6)",55001,575.1,180.9,24.6,116.1,29.9,192.3
20,"Owsley County, Kentucky(7)",21189,574.9,178.9,24.4,115.7,29.9,192.2
21,"Bath County, Kentucky(7)",21011,574.8,176.6,24.3,114.8,29.8,190.9
22,"Lee County, Kentucky(7)",21129,574.7,176.4,24.1,114.7,29.8,190.6
23,"Lee County, Georgia(7)",13177,573.6,176.2,24,113.9,29.3,189.2
24,"Monroe County, Kentucky(7)",21171,572.4,175.4,23.8,113,29.3,187.3
25,"Yukon-Koyukuk Census Area, Alaska(6)",2290,569,174.9,23.7,112.2,29.2,186.1
26,"Livingston County, Kentucky(7)",21139,568.9,174.5,23.7,112.2,29.1,185.1
27,"Scott County, Illinois(7)",17171,568.6,174.4,23.5,111.6,29,185
28,"Taylor County, Kentucky(7)",21217,568.1,174,23.3,111.5,28.7,184.6
29,"Cass County, Iowa(7)",19029,567.8,171.9,23.3,109.3,28.6,184.6
30,"Menard County, Illinois(7)",17129,567.2,170.7,23.3,109.2,28.5,183.9
31,"Clay County, Kentucky(7)",21051,566.4,170.1,23.2,109.2,28,183.8
32,"McDuffie County, Georgia(7)",13189,566.3,169.8,23.1,108.8,28,183
33,"Pleasants County, West Virginia(6)",54073,566.2,169.4,22.8,108.2,28,182.4
34,"Knox County, Kentucky(7)",21121,566.2,169.3,22.7,108.2,27.8,180.4
35,"Lawrence County, Kentucky(7)",21127,565.7,168,22.7,108,27.7,179.2
36,"Marion County, Illinois(7)",17121,565.4,166.7,22.6,107.4,27.7,178.1
37,"Hitchcock County, Nebraska(6)",31087,563.9,166.6,22.4,107.2,27.6,177.6
38,"Jefferson County, New York(7)",36045,562.7,165.8,22.4,107,27.5,177.6
39,"Trousdale County, Tennessee(6)",47169,561.5,164.7,22.4,106.8,27.5,175.6
40,"Bryan County, Georgia(7)",13029,561,164.5,22.4,106.5,27.4,175.3
41,"Iberville Parish, Louisiana(7)",22047,560.3,164.1,22.3,106.4,27,175.1
42,"Stonewall County, Texas(7)",48433,560.2,164.1,22.3,106,27,174.9
43,"Lewis County, West Virginia(6)",54041,560.2,164,22.2,105.4,27,173.8
44,"Harlan County, Kentucky(7)",21095,559.5,163.5,22,105.4,26.9,173.5
45,"Aurora County, South Dakota(6)",46003,559.4,163.3,22,105.4,26.9,173.4
46,"Cape May County, New Jersey(7)",34009,559,163.2,22,105.2,26.8,172.9
47,"McCook County, South Dakota(6)",46087,558.8,162.9,21.9,104.8,26.7,172.4
48,"Greeley County, Nebraska(6)",31077,557.8,162.7,21.9,104.8,26.7,172.2
49,"Adair County, Kentucky(7)",21001,557.4,162.7,21.9,104.7,26.3,172

In [43]:
renamed_cancer.tail()

,County,FIPS,Cancer Incidence Rate Per 100k,Breast Cancer Incidence Rate Per 100k,Leukemia Incidence Rate Per 100k,Lung Cancer Incidence Rate Per 100k,Non-Hodgkin Lymphoma Incidence Rate Per 100k,Prostate Cancer Incidence Rate Per 100k
3139,"Wyandotte County, Kansas(6)",20209,data not available,*,*,*,*,data not available
3140,"Wythe County, Virginia(6)",51197,data not available,data not available,*,data not available,*,*
3141,"Yakutat City and Borough, Alaska(6)",2282,*,data not available,*,data not available,*,data not available
3142,"Yellow Medicine County, Minnesota(6)",27173,data not available,*,*,*,*,data not available
3143,"York County, Virginia(6)",51199,data not available,*,*,*,*,*

In [44]:
#removing the trailing 0 thats in the FIPS code column in the cancer dataframe
renamed_cancer['FIPS'] = renamed_cancer['FIPS'].astype(str).str.rstrip('0').str.rstrip('.')
renamed_cancer.head()

,County,FIPS,Cancer Incidence Rate Per 100k,Breast Cancer Incidence Rate Per 100k,Leukemia Incidence Rate Per 100k,Lung Cancer Incidence Rate Per 100k,Non-Hodgkin Lymphoma Incidence Rate Per 100k,Prostate Cancer Incidence Rate Per 100k
0,US (SEER+NPCR)(1),,442.3,127,13.9,54,18.6,110.5
1,"Union County, Florida(6)",12125,1237.4,250.6,56.5,182.9,48.5,295.7
2,"Palo Alto County, Iowa(7)",19147,658.1,239.7,33.6,141.9,47.9,258.5
3,"Treasure County, Montana(6)",30103,652.2,213,29.2,132.3,41.7,229.1
4,"Polk County, Texas(7)",48373,633.6,209.5,27.7,131.5,40.2,226.7

In [45]:
#merging the dataframes now that the datatypes and common column matches up
merged_df = pd.merge(renamed_cancer, reduced_pesticides, on = 'FIPS')
merged_df.head(50)

,County,FIPS,Cancer Incidence Rate Per 100k,Breast Cancer Incidence Rate Per 100k,Leukemia Incidence Rate Per 100k,Lung Cancer Incidence Rate Per 100k,Non-Hodgkin Lymphoma Incidence Rate Per 100k,Prostate Cancer Incidence Rate Per 100k,Insecticide Sum,Herbicide Sum,Fungicide Sum,Adjuvant Sum
0,"Union County, Florida(6)",12125,1237.4,250.6,56.5,182.9,48.5,295.7,253.1,7146.6,241.5,0.0
1,"Palo Alto County, Iowa(7)",19147,658.1,239.7,33.6,141.9,47.9,258.5,5897.5,269873.7,4271.9,0.0
2,"Treasure County, Montana(6)",30103,652.2,213,29.2,132.3,41.7,229.1,839.8,76881.9,488.3,0.0
3,"Polk County, Texas(7)",48373,633.6,209.5,27.7,131.5,40.2,226.7,1.2,1694.6,1.6,0.0
4,"Floyd County, Kentucky(7)",21071,616.8,204.6,27.7,127.7,36.7,225.7,4.2,812.9,3.8,0.0
5,"Logan County, Nebraska(6)",31113,609.8,198.3,27.2,126.4,34.7,219.4,604.5,39672.1,420.4,0.0
6,"Powell County, Kentucky(7)",21197,597.4,196.9,26.5,125.5,32.9,212.1,41.9,9616.7,294.5,0.0
7,"Blaine County, Nebraska(6)",31009,595.9,196.2,26.3,123.6,32.1,207.7,88.5,3928.2,36.5,0.0
8,"Golden Valley County, Montana(6)",30037,589.6,194.9,26.3,123.6,31.6,206.3,544.1,34871.0,165.6,0.0
9,"Lincoln County, Kentucky(7)",21137,584.7,187.3,26.1,123.4,30.8,205.9,299.1,29360.5,491.3,0.0
10,"Logan County, West Virginia(6)",54045,583.8,186.3,26,121.7,30.7,204.9,0.5,286.5,0.4,0.0
11,"Mercer County, Kentucky(7)",21167,581.5,183.5,25.6,119.7,30.2,199,227.7,22779.1,363.8,0.0
12,"Perry County, Kentucky(7)",21193,578.1,183.1,25.3,119.2,30.2,197.1,22.5,1279.5,6.7,0.0
13,"Fleming County, Kentucky(7)",21069,576,182.8,25.2,116.7,30.1,197,266.8,22394.8,457.7,0.0
14,"Grant County, Kentucky(7)",21081,575.7,181.6,24.9,116.7,30,195.2,191.8,3788.2,35.1,0.0
15,"Pickens County, Georgia(7)",13227,575.3,181.5,24.8,116.4,29.9,192.4,15.5,1320.7,4.7,0.0
16,"Adams County, Wisconsin(6)",55001,575.1,180.9,24.6,116.1,29.9,192.3,3618.0,87732.6,3429.6,0.0
17,"Owsley County, Kentucky(7)",21189,574.9,178.9,24.4,115.7,29.9,192.2,24.6,928.8,4.9,0.0
18,"Bath County, Kentucky(7)",21011,574.8,176.6,24.3,114.8,29.8,190.9,120.7,14285.0,264.1,0.0
19,"Lee County, Kentucky(7)",21129,574.7,176.4,24.1,114.7,29.8,190.6,21.7,1037.6,15.3,0.0
20,"Lee County, Georgia(7)",13177,573.6,176.2,24,113.9,29.3,189.2,15784.6,79725.1,5655.5,0.0
21,"Monroe County, Kentucky(7)",21171,572.4,175.4,23.8,113,29.3,187.3,610.6,34454.9,433.9,0.0
22,"Livingston County, Kentucky(7)",21139,568.9,174.5,23.7,112.2,29.1,185.1,706.1,104225.7,1691.3,0.0
23,"Scott County, Illinois(7)",17171,568.6,174.4,23.5,111.6,29,185,3793.1,150070.4,1225.1,0.0
24,"Taylor County, Kentucky(7)",21217,568.1,174,23.3,111.5,28.7,184.6,419.2,40488.6,546.1,0.0
25,"Cass County, Iowa(7)",19029,567.8,171.9,23.3,109.3,28.6,184.6,3057.8,309589.6,2936.7,0.0
26,"Menard County, Illinois(7)",17129,567.2,170.7,23.3,109.2,28.5,183.9,1113.4,200427.9,2680.1,0.0
27,"Clay County, Kentucky(7)",21051,566.4,170.1,23.2,109.2,28,183.8,207.1,2538.7,59.8,0.0
28,"McDuffie County, Georgia(7)",13189,566.3,169.8,23.1,108.8,28,183,471.4,3723.1,126.2,0.0
29,"Pleasants County, West Virginia(6)",54073,566.2,169.4,22.8,108.2,28,182.4,103.1,413.3,9.4,0.0
30,"Knox County, Kentucky(7)",21121,566.2,169.3,22.7,108.2,27.8,180.4,27.0,2497.5,21.3,0.0
31,"Lawrence County, Kentucky(7)",21127,565.7,168,22.7,108,27.7,179.2,18.9,1160.5,13.5,0.0
32,"Marion County, Illinois(7)",17121,565.4,166.7,22.6,107.4,27.7,178.1,1214.3,220311.4,3165.7,0.0
33,"Hitchcock County, Nebraska(6)",31087,563.9,166.6,22.4,107.2,27.6,177.6,4320.9,315298.9,2044.8,0.0
34,"Jefferson County, New York(7)",36045,562.7,165.8,22.4,107,27.5,177.6,2106.1,46950.6,621.5,0.0
35,"Trousdale County, Tennessee(6)",47169,561.5,164.7,22.4,106.8,27.5,175.6,29.1,3902.6,16.7,0.0
36,"Bryan County, Georgia(7)",13029,561,164.5,22.4,106.5,27.4,175.3,572.9,1553.0,190.2,0.0
37,"Iberville Parish, Louisiana(7)",22047,560.3,164.1,22.3,106.4,27,175.1,1525.6,50539.8,552.1,0.0
38,"Stonewall County, Texas(7)",48433,560.2,164.1,22.3,106,27,174.9,1333.1,33344.1,259.3,0.0
39,"Lewis County, West Virginia(6)",54041,560.2,164,22.2,105.4,27,173.8,110.0,1305.6,4.8,0.0
40,"Harlan County, Kentucky(7)",21095,559.5,163.5,22,105.4,26.9,173.5,97.5,34.3,6.4,0.0
41,"Aurora County, South Dakota(6)",46003,559.4,163.3,22,105.4,26.9,173.4,1128.2,130277.8,1716.4,0.0
42,"Cape May County, New Jersey(7)",34009,559,163.2,22,105.2,26.8,172.9,175.7,824.0,51.5,0.0
43,"McCook County, South Dakota(6)",46087,558.8,162.9,21.9,104.8,26.7,172.4,1559.8,83270.4,1197.9,0.0
44,"Greeley County, Nebraska(6)",31077,557.8,162.7,21.9,104.8,26.7,172.2,27303.3,170976.1,4878.6,0.0
45,"Adair County, Kentucky(7)",21001,557.4,162.7,21.9,104.7,26.3,172,269.6,33145.9,376.1,0.0
46,"Montgomery County, Missouri(6)",29139,557.1,162.5,21.9,104.6,26.2,171.7,4899.0,168645.0,2642.3,0.0
47,"Butler County, Kentucky(7)",21031,557.1,162.4,21.8,104.4,26.2,171.3,377.5,59014.7,812.6,0.0
48,"Morgan County, Illinois(7)",17137,556.7,161.9,21.8,104.3,26.2,171.2,8041.5,316975.3,2578.6,0.0
49,"Nassau County, Florida(6)",12089,555.9,161.8,21.8,104.2,26.2,170.8,134.6,2524.3,129.6,0.0

In [46]:
merged_df.tail()

,County,FIPS,Cancer Incidence Rate Per 100k,Breast Cancer Incidence Rate Per 100k,Leukemia Incidence Rate Per 100k,Lung Cancer Incidence Rate Per 100k,Non-Hodgkin Lymphoma Incidence Rate Per 100k,Prostate Cancer Incidence Rate Per 100k,Insecticide Sum,Herbicide Sum,Fungicide Sum,Adjuvant Sum
2769,"Wright County, Minnesota(6)",27171,data not available,data not available,data not available,data not available,data not available,data not available,3639.3,147729.2,5356.3,0.0
2770,"Wyandotte County, Kansas(6)",20209,data not available,*,*,*,*,data not available,1930.5,13745.4,94.4,0.0
2771,"Wythe County, Virginia(6)",51197,data not available,data not available,*,data not available,*,*,228.2,15123.6,280.6,0.0
2772,"Yellow Medicine County, Minnesota(6)",27173,data not available,*,*,*,*,data not available,4553.5,321841.9,2352.8,0.0
2773,"York County, Virginia(6)",51199,data not available,*,*,*,*,*,0.0,38.2,0.2,0.0

In [47]:
merged_df.dtypes

County                                           object
FIPS                                             object
Cancer Incidence Rate Per 100k                   object
Breast Cancer Incidence Rate Per 100k            object
Leukemia Incidence Rate Per 100k                 object
Lung Cancer Incidence Rate Per 100k              object
Non-Hodgkin Lymphoma Incidence Rate Per 100k     object
Prostate Cancer Incidence Rate Per 100k          object
Insecticide Sum                                 float64
Herbicide Sum                                   float64
Fungicide Sum                                   float64
Adjuvant Sum                                    float64
dtype: object

In [48]:
merged_df = merged_df.dropna(how = 'any')
merged_df.tail()

,County,FIPS,Cancer Incidence Rate Per 100k,Breast Cancer Incidence Rate Per 100k,Leukemia Incidence Rate Per 100k,Lung Cancer Incidence Rate Per 100k,Non-Hodgkin Lymphoma Incidence Rate Per 100k,Prostate Cancer Incidence Rate Per 100k,Insecticide Sum,Herbicide Sum,Fungicide Sum,Adjuvant Sum
2769,"Wright County, Minnesota(6)",27171,data not available,data not available,data not available,data not available,data not available,data not available,3639.3,147729.2,5356.3,0.0
2770,"Wyandotte County, Kansas(6)",20209,data not available,*,*,*,*,data not available,1930.5,13745.4,94.4,0.0
2771,"Wythe County, Virginia(6)",51197,data not available,data not available,*,data not available,*,*,228.2,15123.6,280.6,0.0
2772,"Yellow Medicine County, Minnesota(6)",27173,data not available,*,*,*,*,data not available,4553.5,321841.9,2352.8,0.0
2773,"York County, Virginia(6)",51199,data not available,*,*,*,*,*,0.0,38.2,0.2,0.0

In [49]:
value_to_drop = '* '
merged_df = merged_df.drop(merged_df[merged_df['Cancer Incidence Rate Per 100k'] == value_to_drop].index)
merged_df.tail()

,County,FIPS,Cancer Incidence Rate Per 100k,Breast Cancer Incidence Rate Per 100k,Leukemia Incidence Rate Per 100k,Lung Cancer Incidence Rate Per 100k,Non-Hodgkin Lymphoma Incidence Rate Per 100k,Prostate Cancer Incidence Rate Per 100k,Insecticide Sum,Herbicide Sum,Fungicide Sum,Adjuvant Sum
2769,"Wright County, Minnesota(6)",27171,data not available,data not available,data not available,data not available,data not available,data not available,3639.3,147729.2,5356.3,0.0
2770,"Wyandotte County, Kansas(6)",20209,data not available,*,*,*,*,data not available,1930.5,13745.4,94.4,0.0
2771,"Wythe County, Virginia(6)",51197,data not available,data not available,*,data not available,*,*,228.2,15123.6,280.6,0.0
2772,"Yellow Medicine County, Minnesota(6)",27173,data not available,*,*,*,*,data not available,4553.5,321841.9,2352.8,0.0
2773,"York County, Virginia(6)",51199,data not available,*,*,*,*,*,0.0,38.2,0.2,0.0

In [50]:
value_to_drop = '* '
merged_df = merged_df.drop(merged_df[merged_df['Breast Cancer Incidence Rate Per 100k'] == value_to_drop].index)
merged_df.tail()

,County,FIPS,Cancer Incidence Rate Per 100k,Breast Cancer Incidence Rate Per 100k,Leukemia Incidence Rate Per 100k,Lung Cancer Incidence Rate Per 100k,Non-Hodgkin Lymphoma Incidence Rate Per 100k,Prostate Cancer Incidence Rate Per 100k,Insecticide Sum,Herbicide Sum,Fungicide Sum,Adjuvant Sum
2765,"Wilson County, Kansas(6)",20205,data not available,data not available,*,data not available,*,data not available,41546.9,150913.8,2699.7,0.0
2767,"Wise County, Virginia(6)",51195,data not available,data not available,*,data not available,*,*,179.8,1484.6,15.3,0.0
2768,"Woodson County, Kansas(6)",20207,data not available,data not available,*,data not available,*,data not available,24702.8,94125.9,1296.3,0.0
2769,"Wright County, Minnesota(6)",27171,data not available,data not available,data not available,data not available,data not available,data not available,3639.3,147729.2,5356.3,0.0
2771,"Wythe County, Virginia(6)",51197,data not available,data not available,*,data not available,*,*,228.2,15123.6,280.6,0.0

In [51]:
value_to_drop = '* '
merged_df = merged_df.drop(merged_df[merged_df['Leukemia Incidence Rate Per 100k'] == value_to_drop].index)
merged_df.tail()

,County,FIPS,Cancer Incidence Rate Per 100k,Breast Cancer Incidence Rate Per 100k,Leukemia Incidence Rate Per 100k,Lung Cancer Incidence Rate Per 100k,Non-Hodgkin Lymphoma Incidence Rate Per 100k,Prostate Cancer Incidence Rate Per 100k,Insecticide Sum,Herbicide Sum,Fungicide Sum,Adjuvant Sum
2746,"Wallace County, Kansas(6)",20199,data not available,data not available,data not available,data not available,*,data not available,4177.5,304158.8,2703.3,0.0
2748,"Warren County, Virginia(6)",51187,data not available,data not available,data not available,*,data not available,data not available,547.1,3226.9,45.1,0.0
2762,"Whitley County, Indiana(6)",18183,data not available,data not available,data not available,data not available,data not available,data not available,2170.2,144686.3,2093.8,0.0
2764,"Wilkin County, Minnesota(6)",27167,data not available,data not available,data not available,data not available,data not available,*,5252.9,249602.4,6507.0,0.0
2769,"Wright County, Minnesota(6)",27171,data not available,data not available,data not available,data not available,data not available,data not available,3639.3,147729.2,5356.3,0.0

In [52]:
value_to_drop = '* '
merged_df = merged_df.drop(merged_df[merged_df['Lung Cancer Incidence Rate Per 100k'] == value_to_drop].index)
merged_df.tail()

,County,FIPS,Cancer Incidence Rate Per 100k,Breast Cancer Incidence Rate Per 100k,Leukemia Incidence Rate Per 100k,Lung Cancer Incidence Rate Per 100k,Non-Hodgkin Lymphoma Incidence Rate Per 100k,Prostate Cancer Incidence Rate Per 100k,Insecticide Sum,Herbicide Sum,Fungicide Sum,Adjuvant Sum
2743,"Wabasha County, Minnesota(6)",27157,data not available,data not available,data not available,data not available,*,data not available,3272.1,168710.0,2407.0,0.0
2746,"Wallace County, Kansas(6)",20199,data not available,data not available,data not available,data not available,*,data not available,4177.5,304158.8,2703.3,0.0
2762,"Whitley County, Indiana(6)",18183,data not available,data not available,data not available,data not available,data not available,data not available,2170.2,144686.3,2093.8,0.0
2764,"Wilkin County, Minnesota(6)",27167,data not available,data not available,data not available,data not available,data not available,*,5252.9,249602.4,6507.0,0.0
2769,"Wright County, Minnesota(6)",27171,data not available,data not available,data not available,data not available,data not available,data not available,3639.3,147729.2,5356.3,0.0

In [53]:
value_to_drop = '* '
merged_df = merged_df.drop(merged_df[merged_df['Non-Hodgkin Lymphoma Incidence Rate Per 100k'] == value_to_drop].index)
merged_df.tail()

,County,FIPS,Cancer Incidence Rate Per 100k,Breast Cancer Incidence Rate Per 100k,Leukemia Incidence Rate Per 100k,Lung Cancer Incidence Rate Per 100k,Non-Hodgkin Lymphoma Incidence Rate Per 100k,Prostate Cancer Incidence Rate Per 100k,Insecticide Sum,Herbicide Sum,Fungicide Sum,Adjuvant Sum
2712,"St. Joseph County, Indiana(6)",18141,data not available,data not available,data not available,data not available,data not available,*,3571.7,137269.5,1550.7,0.0
2739,"Vanderburgh County, Indiana(6)",18163,data not available,data not available,data not available,data not available,data not available,data not available,624.3,100731.3,1261.7,0.0
2762,"Whitley County, Indiana(6)",18183,data not available,data not available,data not available,data not available,data not available,data not available,2170.2,144686.3,2093.8,0.0
2764,"Wilkin County, Minnesota(6)",27167,data not available,data not available,data not available,data not available,data not available,*,5252.9,249602.4,6507.0,0.0
2769,"Wright County, Minnesota(6)",27171,data not available,data not available,data not available,data not available,data not available,data not available,3639.3,147729.2,5356.3,0.0

In [54]:
value_to_drop = '* '
merged_df = merged_df.drop(merged_df[merged_df['Prostate Cancer Incidence Rate Per 100k'] == value_to_drop].index)
merged_df.tail()

,County,FIPS,Cancer Incidence Rate Per 100k,Breast Cancer Incidence Rate Per 100k,Leukemia Incidence Rate Per 100k,Lung Cancer Incidence Rate Per 100k,Non-Hodgkin Lymphoma Incidence Rate Per 100k,Prostate Cancer Incidence Rate Per 100k,Insecticide Sum,Herbicide Sum,Fungicide Sum,Adjuvant Sum
2696,"Scott County, Virginia(6)",51169,data not available,data not available,data not available,data not available,data not available,data not available,55.7,8569.8,16.5,0.0
2704,"Sherman County, Kansas(6)",20181,data not available,data not available,data not available,data not available,data not available,data not available,10882.7,615708.9,5935.7,0.0
2739,"Vanderburgh County, Indiana(6)",18163,data not available,data not available,data not available,data not available,data not available,data not available,624.3,100731.3,1261.7,0.0
2762,"Whitley County, Indiana(6)",18183,data not available,data not available,data not available,data not available,data not available,data not available,2170.2,144686.3,2093.8,0.0
2769,"Wright County, Minnesota(6)",27171,data not available,data not available,data not available,data not available,data not available,data not available,3639.3,147729.2,5356.3,0.0

In [55]:
value_to_drop = 'data not available '
merged_df = merged_df.drop(merged_df[merged_df['Cancer Incidence Rate Per 100k'] == value_to_drop].index)
merged_df.tail()

,County,FIPS,Cancer Incidence Rate Per 100k,Breast Cancer Incidence Rate Per 100k,Leukemia Incidence Rate Per 100k,Lung Cancer Incidence Rate Per 100k,Non-Hodgkin Lymphoma Incidence Rate Per 100k,Prostate Cancer Incidence Rate Per 100k,Insecticide Sum,Herbicide Sum,Fungicide Sum,Adjuvant Sum
2202,"Kimball County, Nebraska(6)",31105,363.2,63.9,data not available,15.1,data not available,55.8,1518.4,185927.7,2083.5,0.0
2337,"Concho County, Texas(7)",48095,297.7,data not available,data not available,data not available,data not available,data not available,3364.8,81478.3,786.9,0.0
2343,"Sublette County, Wyoming(6)",56035,290.4,data not available,data not available,data not available,data not available,data not available,1061.9,2393.7,0.0,0.0
2347,"Ferry County, Washington(6)",53019,283.7,data not available,data not available,data not available,data not available,data not available,438.6,3225.6,162.1,0.0
2359,"Holmes County, Florida(6)",12059,267.2,data not available,data not available,data not available,data not available,data not available,3337.8,17621.8,2023.1,0.0

In [56]:
value_to_drop = 'data not available '
merged_df = merged_df.drop(merged_df[merged_df['Breast Cancer Incidence Rate Per 100k'] == value_to_drop].index)
merged_df.tail()

,County,FIPS,Cancer Incidence Rate Per 100k,Breast Cancer Incidence Rate Per 100k,Leukemia Incidence Rate Per 100k,Lung Cancer Incidence Rate Per 100k,Non-Hodgkin Lymphoma Incidence Rate Per 100k,Prostate Cancer Incidence Rate Per 100k,Insecticide Sum,Herbicide Sum,Fungicide Sum,Adjuvant Sum
2162,"Schoolcraft County, Michigan(6)",26153,375.6,81.8,data not available,29.9,data not available,65.7,29.9,1470.4,74.6,0.0
2163,"Jasper County, South Carolina(6)",45053,375.5,81.6,data not available,29.9,data not available,65.5,271.0,2014.1,38.8,0.0
2180,"Mackinac County, Michigan(6)",26097,370.8,78.6,data not available,27.2,data not available,61.1,237.7,3771.9,126.6,0.0
2184,"Union County, New Mexico(7)",35059,369.5,76.9,data not available,26.3,data not available,60.2,369.5,22092.6,295.1,0.0
2202,"Kimball County, Nebraska(6)",31105,363.2,63.9,data not available,15.1,data not available,55.8,1518.4,185927.7,2083.5,0.0

In [57]:
value_to_drop = 'data not available '
merged_df = merged_df.drop(merged_df[merged_df['Leukemia Incidence Rate Per 100k'] == value_to_drop].index)
merged_df.tail()

,County,FIPS,Cancer Incidence Rate Per 100k,Breast Cancer Incidence Rate Per 100k,Leukemia Incidence Rate Per 100k,Lung Cancer Incidence Rate Per 100k,Non-Hodgkin Lymphoma Incidence Rate Per 100k,Prostate Cancer Incidence Rate Per 100k,Insecticide Sum,Herbicide Sum,Fungicide Sum,Adjuvant Sum
1592,"Hickman County, Kentucky(7)",21105,436.4,113,7.3,54.6,14.1,95.9,1753.6,245496.5,5383.3,0.0
1593,"Butler County, Nebraska(6)",31023,436.3,113,6.9,54.5,14.1,95.8,2697.3,370666.0,4818.5,0.0
1594,"Westmoreland County, Pennsylvania(6)",42129,436.3,112.9,6.4,54.5,14.1,95.8,1796.6,28806.5,839.8,0.0
1595,"New York County, New York(7)",36061,436.2,112.9,6.3,54.5,14.1,95.8,0.0,0.0,0.0,0.0
1596,"Attala County, Mississippi(6)",28007,436.2,112.9,4.5,54.5,14.1,95.8,3674.7,21905.1,277.8,0.0

In [58]:
merged_df = merged_df.astype({'Cancer Incidence Rate Per 100k': float,
                             'Breast Cancer Incidence Rate Per 100k': float,
                             'Leukemia Incidence Rate Per 100k': float,
                             'Non-Hodgkin Lymphoma Incidence Rate Per 100k': float,
                             'Prostate Cancer Incidence Rate Per 100k': float,
                             'Lung Cancer Incidence Rate Per 100k': float}, errors = 'raise')

In [59]:
merged_df.dtypes

County                                           object
FIPS                                             object
Cancer Incidence Rate Per 100k                  float64
Breast Cancer Incidence Rate Per 100k           float64
Leukemia Incidence Rate Per 100k                float64
Lung Cancer Incidence Rate Per 100k             float64
Non-Hodgkin Lymphoma Incidence Rate Per 100k    float64
Prostate Cancer Incidence Rate Per 100k         float64
Insecticide Sum                                 float64
Herbicide Sum                                   float64
Fungicide Sum                                   float64
Adjuvant Sum                                    float64
dtype: object

In [60]:
merged_df.head(50)

,County,FIPS,Cancer Incidence Rate Per 100k,Breast Cancer Incidence Rate Per 100k,Leukemia Incidence Rate Per 100k,Lung Cancer Incidence Rate Per 100k,Non-Hodgkin Lymphoma Incidence Rate Per 100k,Prostate Cancer Incidence Rate Per 100k,Insecticide Sum,Herbicide Sum,Fungicide Sum,Adjuvant Sum
0,"Union County, Florida(6)",12125,1237.4,250.6,56.5,182.9,48.5,295.7,253.1,7146.6,241.5,0.0
1,"Palo Alto County, Iowa(7)",19147,658.1,239.7,33.6,141.9,47.9,258.5,5897.5,269873.7,4271.9,0.0
2,"Treasure County, Montana(6)",30103,652.2,213.0,29.2,132.3,41.7,229.1,839.8,76881.9,488.3,0.0
3,"Polk County, Texas(7)",48373,633.6,209.5,27.7,131.5,40.2,226.7,1.2,1694.6,1.6,0.0
4,"Floyd County, Kentucky(7)",21071,616.8,204.6,27.7,127.7,36.7,225.7,4.2,812.9,3.8,0.0
5,"Logan County, Nebraska(6)",31113,609.8,198.3,27.2,126.4,34.7,219.4,604.5,39672.1,420.4,0.0
6,"Powell County, Kentucky(7)",21197,597.4,196.9,26.5,125.5,32.9,212.1,41.9,9616.7,294.5,0.0
7,"Blaine County, Nebraska(6)",31009,595.9,196.2,26.3,123.6,32.1,207.7,88.5,3928.2,36.5,0.0
8,"Golden Valley County, Montana(6)",30037,589.6,194.9,26.3,123.6,31.6,206.3,544.1,34871.0,165.6,0.0
9,"Lincoln County, Kentucky(7)",21137,584.7,187.3,26.1,123.4,30.8,205.9,299.1,29360.5,491.3,0.0
10,"Logan County, West Virginia(6)",54045,583.8,186.3,26.0,121.7,30.7,204.9,0.5,286.5,0.4,0.0
11,"Mercer County, Kentucky(7)",21167,581.5,183.5,25.6,119.7,30.2,199.0,227.7,22779.1,363.8,0.0
12,"Perry County, Kentucky(7)",21193,578.1,183.1,25.3,119.2,30.2,197.1,22.5,1279.5,6.7,0.0
13,"Fleming County, Kentucky(7)",21069,576.0,182.8,25.2,116.7,30.1,197.0,266.8,22394.8,457.7,0.0
14,"Grant County, Kentucky(7)",21081,575.7,181.6,24.9,116.7,30.0,195.2,191.8,3788.2,35.1,0.0
15,"Pickens County, Georgia(7)",13227,575.3,181.5,24.8,116.4,29.9,192.4,15.5,1320.7,4.7,0.0
16,"Adams County, Wisconsin(6)",55001,575.1,180.9,24.6,116.1,29.9,192.3,3618.0,87732.6,3429.6,0.0
17,"Owsley County, Kentucky(7)",21189,574.9,178.9,24.4,115.7,29.9,192.2,24.6,928.8,4.9,0.0
18,"Bath County, Kentucky(7)",21011,574.8,176.6,24.3,114.8,29.8,190.9,120.7,14285.0,264.1,0.0
19,"Lee County, Kentucky(7)",21129,574.7,176.4,24.1,114.7,29.8,190.6,21.7,1037.6,15.3,0.0
20,"Lee County, Georgia(7)",13177,573.6,176.2,24.0,113.9,29.3,189.2,15784.6,79725.1,5655.5,0.0
21,"Monroe County, Kentucky(7)",21171,572.4,175.4,23.8,113.0,29.3,187.3,610.6,34454.9,433.9,0.0
22,"Livingston County, Kentucky(7)",21139,568.9,174.5,23.7,112.2,29.1,185.1,706.1,104225.7,1691.3,0.0
23,"Scott County, Illinois(7)",17171,568.6,174.4,23.5,111.6,29.0,185.0,3793.1,150070.4,1225.1,0.0
24,"Taylor County, Kentucky(7)",21217,568.1,174.0,23.3,111.5,28.7,184.6,419.2,40488.6,546.1,0.0
25,"Cass County, Iowa(7)",19029,567.8,171.9,23.3,109.3,28.6,184.6,3057.8,309589.6,2936.7,0.0
26,"Menard County, Illinois(7)",17129,567.2,170.7,23.3,109.2,28.5,183.9,1113.4,200427.9,2680.1,0.0
27,"Clay County, Kentucky(7)",21051,566.4,170.1,23.2,109.2,28.0,183.8,207.1,2538.7,59.8,0.0
28,"McDuffie County, Georgia(7)",13189,566.3,169.8,23.1,108.8,28.0,183.0,471.4,3723.1,126.2,0.0
29,"Pleasants County, West Virginia(6)",54073,566.2,169.4,22.8,108.2,28.0,182.4,103.1,413.3,9.4,0.0
30,"Knox County, Kentucky(7)",21121,566.2,169.3,22.7,108.2,27.8,180.4,27.0,2497.5,21.3,0.0
31,"Lawrence County, Kentucky(7)",21127,565.7,168.0,22.7,108.0,27.7,179.2,18.9,1160.5,13.5,0.0
32,"Marion County, Illinois(7)",17121,565.4,166.7,22.6,107.4,27.7,178.1,1214.3,220311.4,3165.7,0.0
33,"Hitchcock County, Nebraska(6)",31087,563.9,166.6,22.4,107.2,27.6,177.6,4320.9,315298.9,2044.8,0.0
34,"Jefferson County, New York(7)",36045,562.7,165.8,22.4,107.0,27.5,177.6,2106.1,46950.6,621.5,0.0
35,"Trousdale County, Tennessee(6)",47169,561.5,164.7,22.4,106.8,27.5,175.6,29.1,3902.6,16.7,0.0
36,"Bryan County, Georgia(7)",13029,561.0,164.5,22.4,106.5,27.4,175.3,572.9,1553.0,190.2,0.0
37,"Iberville Parish, Louisiana(7)",22047,560.3,164.1,22.3,106.4,27.0,175.1,1525.6,50539.8,552.1,0.0
38,"Stonewall County, Texas(7)",48433,560.2,164.1,22.3,106.0,27.0,174.9,1333.1,33344.1,259.3,0.0
39,"Lewis County, West Virginia(6)",54041,560.2,164.0,22.2,105.4,27.0,173.8,110.0,1305.6,4.8,0.0
40,"Harlan County, Kentucky(7)",21095,559.5,163.5,22.0,105.4,26.9,173.5,97.5,34.3,6.4,0.0
41,"Aurora County, South Dakota(6)",46003,559.4,163.3,22.0,105.4,26.9,173.4,1128.2,130277.8,1716.4,0.0
42,"Cape May County, New Jersey(7)",34009,559.0,163.2,22.0,105.2,26.8,172.9,175.7,824.0,51.5,0.0
43,"McCook County, South Dakota(6)",46087,558.8,162.9,21.9,104.8,26.7,172.4,1559.8,83270.4,1197.9,0.0
44,"Greeley County, Nebraska(6)",31077,557.8,162.7,21.9,104.8,26.7,172.2,27303.3,170976.1,4878.6,0.0
45,"Adair County, Kentucky(7)",21001,557.4,162.7,21.9,104.7,26.3,172.0,269.6,33145.9,376.1,0.0
46,"Montgomery County, Missouri(6)",29139,557.1,162.5,21.9,104.6,26.2,171.7,4899.0,168645.0,2642.3,0.0
47,"Butler County, Kentucky(7)",21031,557.1,162.4,21.8,104.4,26.2,171.3,377.5,59014.7,812.6,0.0
48,"Morgan County, Illinois(7)",17137,556.7,161.9,21.8,104.3,26.2,171.2,8041.5,316975.3,2578.6,0.0
49,"Nassau County, Florida(6)",12089,555.9,161.8,21.8,104.2,26.2,170.8,134.6,2524.3,129.6,0.0

In [61]:
merged_df = merged_df.drop(columns = ['Adjuvant Sum'])
merged_df.head()

,County,FIPS,Cancer Incidence Rate Per 100k,Breast Cancer Incidence Rate Per 100k,Leukemia Incidence Rate Per 100k,Lung Cancer Incidence Rate Per 100k,Non-Hodgkin Lymphoma Incidence Rate Per 100k,Prostate Cancer Incidence Rate Per 100k,Insecticide Sum,Herbicide Sum,Fungicide Sum
0,"Union County, Florida(6)",12125,1237.4,250.6,56.5,182.9,48.5,295.7,253.1,7146.6,241.5
1,"Palo Alto County, Iowa(7)",19147,658.1,239.7,33.6,141.9,47.9,258.5,5897.5,269873.7,4271.9
2,"Treasure County, Montana(6)",30103,652.2,213.0,29.2,132.3,41.7,229.1,839.8,76881.9,488.3
3,"Polk County, Texas(7)",48373,633.6,209.5,27.7,131.5,40.2,226.7,1.2,1694.6,1.6
4,"Floyd County, Kentucky(7)",21071,616.8,204.6,27.7,127.7,36.7,225.7,4.2,812.9,3.8

In [63]:
#exporting to a csv
#merged_df.to_csv("all_cancer_and_pesticides.csv", index = False, header = True)