In [1]:
import pandas as pd
from pathlib import Path

In [2]:
pesticides_df = pd.read_csv(Path("2019_pesticide_by_county.csv"))
pesticides_df.head()

,AREA_FIPS_CODE,"2,4-D",ACEPHATE,ACETAMIPRID,ACETOCHLOR,ATRAZINE,AZOXYSTROBIN,BENTAZONE,BENZOVINDIFLUPYR,BOSCALID,...,TEBUCONAZOLE,TEBUPIRIMPHOS,TEBUTHIURON,TERBUFOS,TETRACONAZOLE,THIAMETHOXAM,THIOBENCARB,TRICLOPYR,TRIFLOXYSTROBIN,Grand Total
0,10001,12874.8,NaN,NaN,8918.9,32489.9,967.9,NaN,16.2,NaN,...,621.0,NaN,NaN,1895.9,NaN,NaN,NaN,NaN,226.1,213302.8
1,10003,1424.7,2.4,0.9,3130.3,8243.2,301.5,NaN,20.8,NaN,...,189.4,NaN,NaN,637.7,NaN,NaN,NaN,28.5,76.1,64162.0
2,10005,66354.3,NaN,NaN,30403.2,134910.1,3632.5,NaN,31.4,NaN,...,714.7,NaN,NaN,3671.2,NaN,NaN,NaN,NaN,437.9,648243.1
3,12001,12562.9,NaN,NaN,NaN,557.2,342.9,25.4,8.5,114.3,...,663.9,NaN,NaN,78.6,NaN,43.9,NaN,230.5,1.3,25143.6
4,12003,1576.3,NaN,NaN,26.6,146.7,119.0,NaN,17.0,0.1,...,3.8,NaN,NaN,41.8,1.0,NaN,NaN,195.8,0.5,3345.0

In [3]:
pesticides_df = pesticides_df.fillna(0)
pesticides_df.head()

,AREA_FIPS_CODE,"2,4-D",ACEPHATE,ACETAMIPRID,ACETOCHLOR,ATRAZINE,AZOXYSTROBIN,BENTAZONE,BENZOVINDIFLUPYR,BOSCALID,...,TEBUCONAZOLE,TEBUPIRIMPHOS,TEBUTHIURON,TERBUFOS,TETRACONAZOLE,THIAMETHOXAM,THIOBENCARB,TRICLOPYR,TRIFLOXYSTROBIN,Grand Total
0,10001,12874.8,0.0,0.0,8918.9,32489.9,967.9,0.0,16.2,0.0,...,621.0,0.0,0.0,1895.9,0.0,0.0,0.0,0.0,226.1,213302.8
1,10003,1424.7,2.4,0.9,3130.3,8243.2,301.5,0.0,20.8,0.0,...,189.4,0.0,0.0,637.7,0.0,0.0,0.0,28.5,76.1,64162.0
2,10005,66354.3,0.0,0.0,30403.2,134910.1,3632.5,0.0,31.4,0.0,...,714.7,0.0,0.0,3671.2,0.0,0.0,0.0,0.0,437.9,648243.1
3,12001,12562.9,0.0,0.0,0.0,557.2,342.9,25.4,8.5,114.3,...,663.9,0.0,0.0,78.6,0.0,43.9,0.0,230.5,1.3,25143.6
4,12003,1576.3,0.0,0.0,26.6,146.7,119.0,0.0,17.0,0.1,...,3.8,0.0,0.0,41.8,1.0,0.0,0.0,195.8,0.5,3345.0

In [4]:
pesticides_df.info

<bound method DataFrame.info of      AREA_FIPS_CODE       2,4-D   ACEPHATE  ACETAMIPRID  ACETOCHLOR  \
0             10001     12874.8        0.0          0.0      8918.9
1             10003      1424.7        2.4          0.9      3130.3
2             10005     66354.3        0.0          0.0     30403.2
3             12001     12562.9        0.0          0.0         0.0
4             12003      1576.3        0.0          0.0        26.6
...             ...         ...        ...          ...         ...
3059          09009       166.7        0.0         26.6        90.7
3060          09011       398.3        0.0          6.3       687.2
3061          09013       283.1        0.0          9.9       506.8
3062          09015       340.2        0.0         12.6       620.8
3063    Grand Total  22361443.9  5855133.4      66748.7  27712782.3

        ATRAZINE  AZOXYSTROBIN  BENTAZONE  BENZOVINDIFLUPYR  BOSCALID  ...  \
0        32489.9         967.9        0.0              16.2       0.0  ...
1         8243.2         301.5        0.0              20.8       0.0  ...
2       134910.1        3632.5        0.0              31.4       0.0  ...
3          557.2         342.9       25.4               8.5     114.3  ...
4          146.7         119.0        0.0              17.0       0.1  ...
...          ...           ...        ...               ...       ...  ...
3059       176.8           0.1        0.0               0.0      15.7  ...
3060      1137.6           0.1        0.0               0.0       3.2  ...
3061       841.1           0.0        0.0               0.0       2.5  ...
3062      1019.1           0.0        0.0               0.0       7.6  ...
3063  33663059.4     1301556.7  1058728.9          150928.9  372891.2  ...

      TEBUCONAZOLE  TEBUPIRIMPHOS  TEBUTHIURON  TERBUFOS  TETRACONAZOLE  \
0            621.0            0.0          0.0    1895.9            0.0
1            189.4            0.0          0.0     637.7            0.0
2            714.7            0.0          0.0    3671.2            0.0
3            663.9            0.0          0.0      78.6            0.0
4              3.8            0.0          0.0      41.8            1.0
...            ...            ...          ...       ...            ...
3059           0.0            0.0          0.0       0.0            0.0
3060           0.0            0.0          0.0       0.0            0.0
3061           0.0            0.0          0.0       0.0            0.0
3062           0.0            0.0          0.0       0.0            0.0
3063      892076.7       112394.9       1932.1  768589.7       108574.2

      THIAMETHOXAM  THIOBENCARB  TRICLOPYR  TRIFLOXYSTROBIN  Grand Total
0              0.0          0.0        0.0            226.1     213302.8
1              0.0          0.0       28.5             76.1      64162.0
2              0.0          0.0        0.0            437.9     648243.1
3             43.9          0.0      230.5              1.3      25143.6
4              0.0          0.0      195.8              0.5       3345.0
...            ...          ...        ...              ...          ...
3059           3.3          0.0        0.0              9.4       1605.5
3060           2.2          0.0        0.0              1.7       8412.2
3061           6.3          0.0        0.0              1.5       6374.4
3062           2.1          0.0        0.0              4.5       7610.0
3063      145243.1     780582.2  1039730.6         471080.4  341070497.0

[3064 rows x 71 columns]>

In [5]:
pesticides_df.columns

Index(['AREA_FIPS_CODE', '2,4-D', 'ACEPHATE', 'ACETAMIPRID', 'ACETOCHLOR',
       'ATRAZINE', 'AZOXYSTROBIN', 'BENTAZONE', 'BENZOVINDIFLUPYR', 'BOSCALID',
       'BROMACIL', 'BROMOXYNIL', 'CARBARYL', 'CHLORANTRANILIPROLE',
       'CHLORIMURON', 'CHLORPYRIFOS', 'CLOTHIANIDIN', 'CYANTRANILIPROLE',
       'CYPRODINIL', 'DIAZINON', 'DICAMBA', 'DICROTOPHOS', 'DIFLUBENZURON',
       'DIMETHENAMID', 'DIMETHENAMID & DIMETHENAMID-P', 'DIMETHENAMID-P',
       'DIMETHOATE', 'DIMETHOMORPH', 'DINOTEFURAN', 'DIURON', 'ETHOPROPHOS',
       'ETOXAZOLE', 'FIPRONIL', 'FLUOMETURON', 'FLUOPICOLIDE', 'GLYPHOSATE',
       'HALOSULFURON', 'HEXAZINONE', 'IMAZETHAPYR', 'IMIDACLOPRID', 'LINURON',
       'MALATHION', 'METALAXYL', 'METCONAZOLE', 'METHOMYL', 'METHOXYFENOZIDE',
       'METOLACHLOR', 'METOLACHLOR & METOLACHLOR-S', 'METOLACHLOR-S',
       'METRIBUZIN', 'MYCLOBUTANIL', 'ORYZALIN', 'PERMETHRIN',
       'PIPERONYL BUTOXIDE', 'PROPAZINE', 'PROPICONAZOLE', 'PYRACLOSTROBIN',
       'PYRIMETHANIL', 'SIMAZINE', 'SULFENTRAZONE', 'SULFOXAFLOR',
       'TEBUCONAZOLE', 'TEBUPIRIMPHOS', 'TEBUTHIURON', 'TERBUFOS',
       'TETRACONAZOLE', 'THIAMETHOXAM', 'THIOBENCARB', 'TRICLOPYR',
       'TRIFLOXYSTROBIN', 'Grand Total'],
      dtype='object')

In [6]:
pesticides_df = pesticides_df.sort_values("Grand Total", ascending = False)
pesticides_df = pesticides_df.drop(columns='Grand Total')
pesticides_df.head()

,AREA_FIPS_CODE,"2,4-D",ACEPHATE,ACETAMIPRID,ACETOCHLOR,ATRAZINE,AZOXYSTROBIN,BENTAZONE,BENZOVINDIFLUPYR,BOSCALID,...,SULFOXAFLOR,TEBUCONAZOLE,TEBUPIRIMPHOS,TEBUTHIURON,TERBUFOS,TETRACONAZOLE,THIAMETHOXAM,THIOBENCARB,TRICLOPYR,TRIFLOXYSTROBIN
3063,Grand Total,22361443.9,5855133.4,66748.7,27712782.3,33663059.4,1301556.7,1058728.9,150928.9,372891.2,...,91034.5,892076.7,112394.9,1932.1,768589.7,108574.2,145243.1,780582.2,1039730.6,471080.4
2945,06019,18989.8,16922.1,5267.6,0.0,141.4,21419.1,114.4,0.0,5553.0,...,1876.6,6112.7,0.0,0.0,0.0,656.3,2399.1,661.2,267.6,8282.1
1082,28011,89434.5,20784.9,0.0,15978.8,81395.5,3813.7,246.2,72.6,0.0,...,15.2,38.4,0.0,0.0,0.0,289.2,15.9,3199.8,97.6,863.8
2907,05093,25157.6,89512.1,32.1,11367.7,8974.7,9079.7,247.3,42.8,0.0,...,3088.0,746.8,0.0,0.0,0.0,251.5,284.4,27865.1,38.8,457.6
2373,48355,56422.8,2983.5,94.3,21483.1,95689.6,37.8,0.0,0.0,0.0,...,1601.2,4.9,0.0,0.0,0.0,0.0,3116.2,0.0,666.8,0.0

In [7]:
types_df = pd.read_csv("pesticide_types.csv")
types_df.head()

,Name,"2,4-D",ACEPHATE,ACETAMIPRID,ACETOCHLOR,ATRAZINE,AZOXYSTROBIN,BENTAZONE,BENZOVINDIFLUPYR,BOSCALID,...,SULFOXAFLOR,TEBUCONAZOLE,TEBUPIRIMPHOS,TEBUTHIURON,TERBUFOS,TETRACONAZOLE,THIAMETHOXAM,THIOBENCARB,TRICLOPYR,TRIFLOXYSTROBIN
0,Type,Herbicide,Insecticide,Insecticide,Herbicide,Herbicide,Fungicide,Herbicide,Fungicide,Fungicide,...,Insecticide,Fungicide,Insecticide,Herbicide,Insecticide,Fungicide,Insecticide,Herbicide,Herbicide,Fungicide

In [9]:
combined_df = pd.concat([pesticides_df, types_df], ignore_index=False)
combined_df = combined.drop(columns="Name")
combined_df.tail()

,AREA_FIPS_CODE,"2,4-D",ACEPHATE,ACETAMIPRID,ACETOCHLOR,ATRAZINE,AZOXYSTROBIN,BENTAZONE,BENZOVINDIFLUPYR,BOSCALID,...,TEBUCONAZOLE,TEBUPIRIMPHOS,TEBUTHIURON,TERBUFOS,TETRACONAZOLE,THIAMETHOXAM,THIOBENCARB,TRICLOPYR,TRIFLOXYSTROBIN,Name
905,25025,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
948,26083,1.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3025,08065,0.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.0,NaN
1531,36061,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
0,NaN,Herbicide,Insecticide,Insecticide,Herbicide,Herbicide,Fungicide,Herbicide,Fungicide,Fungicide,...,Fungicide,Insecticide,Herbicide,Insecticide,Fungicide,Insecticide,Herbicide,Herbicide,Fungicide,Type

In [13]:
transposed_df = combined_df.transpose()
transposed_df.head()

,3063,2945,1082,2907,2373,328,1671,592,3024,1280,...,1524,1543,2937,94,3050,905,948,3025,1531,0
AREA_FIPS_CODE,Grand Total,06019,28011,05093,48355,17113,38017,20055,08063,30015,...,36047,36085,06003,13053,08117,25025,26083,08065,36061,NaN
"2,4-D",22361443.9,18989.8,89434.5,25157.6,56422.8,35457.7,38150.6,54540.0,95279.2,151462.3,...,0.0,0.0,0.0,5.6,2.1,0.0,1.3,0.6,0.0,Herbicide
ACEPHATE,5855133.4,16922.1,20784.9,89512.1,2983.5,0.0,0.0,3064.2,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Insecticide
ACETAMIPRID,66748.7,5267.6,0.0,32.1,94.3,0.0,0.0,0.0,0.0,0.0,...,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Insecticide
ACETOCHLOR,27712782.3,0.0,15978.8,11367.7,21483.1,27089.3,75010.0,128203.8,46897.9,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Herbicide

In [18]:
transposed_df.groupby(by=[0])

ValueError: Grouper for '0' not 1-dimensional